Private ['_u'];

//--- US Light Vehicles.
//_u = ['rhsusf_M1084A1P2_WD_fmtv_usarmy'];
_u = ['B_Boat_Transport_01_F'];
_u = _u + ['B_Lifeboat'];
if (WF_Camo) then {
// rpt error fix if ((missionNamespace getVariable "WFBE_SUPPLYSYSTEM") == 0) then {_u = _u + [''];_u = _u + [''];_u = _u + ['']};
_u = _u + ['Rwm_hemt_suply_truck'];
_u = _u + ['Rwm_M107_supply_truck'];
_u = _u + ['rhsusf_M978A4_Service_Truck_d'];
_u = _u + ['rhsusf_M977A4_enginer_truck_M2_usarmy_d'];
_u = _u + ['rhsusf_m1025_d_m2'];
_u = _u + ['rhsusf_m1025_d_Mk19'];
_u = _u + ['rhsusf_m998_d_4dr'];
_u = _u + ['rhsusf_M1117_D'];
_u = _u + ['rhsusf_M1220_usarmy_d'];
_u = _u + ['rhsusf_M1220_M153_M2_usarmy_d'];
_u = _u + ['rhsusf_M1220_M2_usarmy_d'];
_u = _u + ['rhsusf_M1220_MK19_usarmy_d'];
_u = _u + ['rhsusf_M1230a1_usarmy_d'];
_u = _u + ['rhsusf_M1078A1P2_D_fmtv_usarmy'];
_u = _u + ['rhsusf_rg33_usmc_d'];
_u = _u + ['rhsusf_rg33_m2_usmc_d'];
_u = _u + ['rhsusf_M1078A1R_SOV_M2_D_fmtv_socom'];
_u = _u + ['rhsusf_mrzr4_d'];
_u = _u + ['rhsusf_m113d_usarmy_supply'];
_u = _u + ['rhsusf_m998_ambu_d'];
_u = _u + ['rhsusf_mkvsoc'];
_u = _u + ['rhsusf_m966_d'];
_u = _u + ['rhsusf_M142_usarmy_D'];
_u = _u + ['rhsusf_CGRCAT1A2_M2_usmc_d'];
_u = _u + ['rhsusf_CGRCAT1A2_Mk19_usmc_d'];
_u = _u + ['B_SDV_01_F'];
_u = _u + ['B_G_Quadbike_01_F'];
_u = _u + ['B_G_Boat_Transport_01_F'];
_u = _u + ['B_Boat_Armed_01_minigun_F'];
_u = _u + ['B_T_Lifeboat'];
_u = _u + ['Rwm_Lav25A2'];
_u = _u + ['Rwm_Lav_25_ambu'];
_u = _u + ['RWM_ACR_Pandur_II'];
_u = _u + ['RWM_ACR_Pandur_II_D'];
_u = _u + ['RWM_oshkosh_M_ATV_ambu_d'];
_u = _u + ['B_T_MRAP_01_F'];
} else {
// rpt error fix if ((missionNamespace getVariable "WFBE_SUPPLYSYSTEM") == 0) then {_u = _u + [''];_u = _u + [''];_u = _u + ['']};
_u = _u + ['Rwm_hemt_suply_truck'];
_u = _u + ['Rwm_M107_supply_truck'];
_u = _u + ['rhsusf_M978A4_Service_Truck_d'];
_u = _u + ['rhsusf_M977A4_enginer_truck_M2_usarmy_d'];
_u = _u + ['rhsusf_m1025_d_m2'];
_u = _u + ['rhsusf_m1025_d_Mk19'];
_u = _u + ['rhsusf_m998_d_4dr'];
_u = _u + ['rhsusf_M1117_D'];
_u = _u + ['rhsusf_M1220_usarmy_d'];
_u = _u + ['rhsusf_M1220_M153_M2_usarmy_d'];
_u = _u + ['rhsusf_M1220_M2_usarmy_d'];
_u = _u + ['rhsusf_M1220_MK19_usarmy_d'];
_u = _u + ['rhsusf_M1230a1_usarmy_d'];
_u = _u + ['rhsusf_M1078A1P2_D_fmtv_usarmy'];
_u = _u + ['rhsusf_rg33_usmc_d'];
_u = _u + ['rhsusf_rg33_m2_usmc_d'];
_u = _u + ['rhsusf_M1078A1R_SOV_M2_D_fmtv_socom'];
_u = _u + ['rhsusf_mrzr4_d'];
_u = _u + ['rhsusf_m113d_usarmy_supply'];
_u = _u + ['rhsusf_m998_ambu_d'];
_u = _u + ['rhsusf_mkvsoc'];
_u = _u + ['rhsusf_m966_d'];
_u = _u + ['rhsusf_M142_usarmy_D'];
_u = _u + ['rhsusf_CGRCAT1A2_M2_usmc_d'];
_u = _u + ['rhsusf_CGRCAT1A2_Mk19_usmc_d'];
_u = _u + ['B_SDV_01_F'];
_u = _u + ['B_G_Quadbike_01_F'];
_u = _u + ['B_G_Boat_Transport_01_F'];
_u = _u + ['B_Boat_Armed_01_minigun_F'];
_u = _u + ['B_T_Lifeboat'];
_u = _u + ['Rwm_Lav25A2'];
_u = _u + ['Rwm_Lav_25_ambu'];
_u = _u + ['RWM_ACR_Pandur_II'];
_u = _u + ['RWM_ACR_Pandur_II_D'];
_u = _u + ['RWM_oshkosh_M_ATV_ambu_d'];
_u = _u + ['B_T_MRAP_01_F'];
};
_u