/* RU Loadout */
Private ['_tiMode'];
_tiMode = 'WFBE_THERMALIMAGING' Call GetNamespace;
_tiMode = if (_tiMode == 1 || _tiMode == 3) then {true} else {false};

if (!isServer || local player) then {
if (side player == EAST) then {
/* Misc. */
_w = ['MediKit'];
_w = _w + ['ToolKit'];
_w = _w + ['ItemCompass'];
_w = _w + ['ItemGPS'];
_w = _w + ['ItemMap'];
_w = _w + ['ItemRadio'];
_w = _w + ['ItemWatch'];
_w = _w + ['MineDetector'];
_w = _w + ['O_UavTerminal'];
_w = _w + ['FirstAidKit'];
WF_Logic setVariable ['miscClasses',_w];

/* Magazines. */
_m = ["rhs_100Rnd_762x54mmR"];
_m = _m + ['rhs_100Rnd_762x54mmR_7BZ3'];
_m = _m + ['rhs_100Rnd_762x54mmR_7N13'];
_m = _m + ['rhs_100Rnd_762x54mmR_7N26'];
_m = _m + ['rhs_100Rnd_762x54mmR_green'];
_m = _m + ['rhs_10Rnd_762x54mmR_7N1'];
_m = _m + ['rhs_10rnd_9x39mm_SP5'];
_m = _m + ['rhs_10rnd_9x39mm_SP6'];
_m = _m + ['rhs_20rnd_9x39mm_SP5'];
_m = _m + ['rhs_20rnd_9x39mm_SP6'];
_m = _m + ['rhs_30Rnd_545x39_7N10_AK'];
_m = _m + ['rhs_30Rnd_545x39_7N22_AK'];
_m = _m + ['rhs_30Rnd_545x39_7N6_AK'];
_m = _m + ['rhs_30Rnd_545x39_7U1_AK'];
_m = _m + ['rhs_30Rnd_545x39_AK'];
_m = _m + ['rhs_30Rnd_545x39_AK_green'];
_m = _m + ['rhs_30Rnd_545x39_AK_no_tracers'];
_m = _m + ['rhs_30Rnd_762x39mm'];
_m = _m + ['rhs_30Rnd_762x39mm_89'];
_m = _m + ['rhs_30Rnd_762x39mm_tracer'];
_m = _m + ['rhs_30Rnd_762x39mm_U'];
_m = _m + ['rhs_45Rnd_545X39_7N10_AK'];
_m = _m + ['rhs_45Rnd_545X39_7N22_AK'];
_m = _m + ['rhs_45Rnd_545X39_7N6_AK'];
_m = _m + ['rhs_45Rnd_545X39_7U1_AK'];
_m = _m + ['rhs_45Rnd_545X39_AK'];
_m = _m + ['rhs_45Rnd_545X39_AK_Green'];
_m = _m + ['rhs_GDM40'];
_m = _m + ['rhs_GRD40_Green'];
_m = _m + ['rhs_GRD40_Red'];
_m = _m + ['rhs_GRD40_White'];
_m = _m + ['rhs_launcher_dummy_mag'];
_m = _m + ['rhs_mag_9k38_rocket'];
_m = _m + ['rhs_mag_9x18_12_57N181S'];
_m = _m + ['rhs_mag_9x18_8_57N181S'];
_m = _m + ['rhs_mag_9x19_17'];
_m = _m + ['rhs_mag_9x19mm_7n21_20'];
_m = _m + ['rhs_mag_9x19mm_7n21_44'];
_m = _m + ['rhs_mag_9x19mm_7n31_20'];
_m = _m + ['rhs_mag_9x19mm_7n31_44'];
_m = _m + ['rhs_rpg18_mag'];
_m = _m + ['Vorona_HE'];
_m = _m + ['Vorona_HEAT'];
_m = _m + ['rhs_rpg26_mag'];
_m = _m + ['rhs_rpg7_OG7V_mag'];
_m = _m + ['rhs_rpg7_PG7V_mag'];
_m = _m + ['rhs_rpg7_PG7VL_mag'];
_m = _m + ['rhs_rpg7_PG7VM_mag'];
_m = _m + ['rhs_rpg7_PG7VR_mag'];
_m = _m + ['rhs_rpg7_PG7VS_mag'];
_m = _m + ['rhs_rpg7_TBG7V_mag'];
_m = _m + ['rhs_rpg7_type69_airburst_mag'];
_m = _m + ['rhs_rshg2_mag'];
_m = _m + ['rhs_VG40MD_Green'];
_m = _m + ['rhs_VG40MD_Red'];
_m = _m + ['rhs_VG40MD_White'];
_m = _m + ['rhs_VG40OP_green'];
_m = _m + ['rhs_VG40OP_red'];
_m = _m + ['rhs_VG40OP_white'];
_m = _m + ['rhs_VG40SZ'];
_m = _m + ['rhs_VG40TB'];
_m = _m + ['rhs_VOG25'];
_m = _m + ['rhs_VOG25P'];
_m = _m + ['rhs_mag_rsp30_green'];
_m = _m + ['rhs_mag_rsp30_red'];
_m = _m + ['rhs_mag_rsp30_white'];
_m = _m + ['rhs_mag_nspd'];
_m = _m + ['rhs_mag_nspn_green'];
_m = _m + ['rhs_mag_nspn_red'];
_m = _m + ['rhs_mag_nspn_yellow'];
_m = _m + ['rhsgref_mag_rkg3em'];
_m = _m + ['rhs_LaserFCSMag'];
_m = _m + ['rhs_LaserMag'];
_m = _m + ['rhs_mag_762x25_8'];
_m = _m + ['rhs_30Rnd_762x39mm_Savz58'];
_m = _m + ['rhs_30Rnd_762x39mm_Savz58_tracer'];
_m = _m + ['rhsgref_10rnd_765x17_vz61'];
_m = _m + ['rhsgref_10Rnd_792x57_m76'];
_m = _m + ['rhsgref_1Rnd_00Buck'];
_m = _m + ['rhsgref_1Rnd_Slug'];
_m = _m + ['rhsgref_20rnd_765x17_vz61'];
_m = _m + ['rhsgref_30rnd_556x45_m21'];
_m = _m + ['rhsgref_30rnd_556x45_m21_t'];
_m = _m + ['rhsgref_5Rnd_762x54_m38'];
_m = _m + ['rhsgref_5Rnd_792x57_kar98k'];
_m = _m + ['rhssaf_100rnd_556x45_EPR_G36'];
_m = _m + ['rhssaf_10Rnd_792x57_m76_tracer'];
_m = _m + ['rhssaf_250Rnd_762x54R'];
_m = _m + ['rhssaf_30rnd_556x45_EPR_G36'];
_m = _m + ['rhssaf_30rnd_556x45_MDIM_G36'];
_m = _m + ['rhssaf_30rnd_556x45_SOST_G36'];
_m = _m + ['rhssaf_30rnd_556x45_SPR_G36'];
_m = _m + ['rhssaf_30rnd_556x45_TDIM_G36'];
_m = _m + ['rhssaf_30rnd_556x45_Tracers_G36'];
_m = _m + ['rhs_mag_M397_HET'];
_m = _m + ['rhs_mag_m4009'];
_m = _m + ['rhs_mag_M433_HEDP'];
_m = _m + ['rhs_mag_M441_HE'];
_m = _m + ['rhs_mag_m576'];
_m = _m + ['rhs_mag_M585_white'];
_m = _m + ['rhs_mag_m661_green'];
_m = _m + ['rhs_mag_m662_red'];
_m = _m + ['rhs_mag_m713_Red'];
_m = _m + ['rhs_mag_m714_White'];
_m = _m + ['rhs_mag_m715_Green'];
_m = _m + ['rhs_mag_m716_yellow'];
_m = _m + ['rhs_mag_M781_Practice'];
_m = _m + ['rhsusf_5Rnd_doomsday_Buck'];
_m = _m + ['rhsusf_5Rnd_FRAG'];
_m = _m + ['rhsusf_5Rnd_HE'];
_m = _m + ['rhsusf_5Rnd_Slug'];
_m = _m + ['rhsusf_8Rnd_00Buck'];
_m = _m + ['rhsusf_8Rnd_doomsday_Buck'];
_m = _m + ['rhsusf_8Rnd_FRAG'];
_m = _m + ['rhsusf_8Rnd_HE'];
_m = _m + ['rhsusf_8Rnd_Slug'];
_m = _m + ['rhs_fgm148_magazine_AT']; //added for balance
_m = _m + ['KA_VC1_Flamethrower_Mag'];
WF_Logic setVariable ['magazineClasses',_m];

/* Primary. */

 _w = ['rhs_weap_m38'];
 _w = _w + ['rhs_weap_Izh18'];
 _w = _w + ['rhs_weap_savz61'];
 _w = _w + ['rhs_weap_akm'];
 _w = _w + ['rhs_weap_akm_gp25'];
 _w = _w + ['rhs_weap_akms'];
 _w = _w + ['rhs_weap_akms_gp25'];
 _w = _w + ['rhs_weap_savz58p'];
 _w = _w + ['rhs_weap_savz58v'];
 _w = _w + ['rhs_weap_pp2000'];
 _w = _w + ['rhs_weap_M590_8RD'];
 _w = _w + ['rhs_weap_M590_5RD'];
 _w = _w + ['rhs_weap_m84'];
 _w = _w + ['rhs_weap_ak74'];
 _w = _w + ['rhs_weap_ak74_gp25'];
 _w = _w + ['rhs_weap_aks74'];
 _w = _w + ['rhs_weap_aks74_gp25'];
 _w = _w + ['rhs_weap_m76'];
 _w = _w + ['rhs_weap_ak103'];
 _w = _w + ['rhs_weap_pkp']; 
 _w = _w + ['rhs_weap_ak103_gp25'];
 _w = _w + ['rhs_weap_ak105'];
 _w = _w + ['rhs_weap_ak105_npz'];
 _w = _w + ['rhs_weap_ak105_zenitco01'];
 _w = _w + ['rhs_weap_ak105_zenitco01_b33'];
 _w = _w + ['rhs_weap_vss_grip'];
 _w = _w + ['rhs_weap_asval'];
 _w = _w + ['rhs_weap_asval_grip'];
 _w = _w + ['rhs_weap_t5000'];
 _w = _w + ['rhs_weap_savz58v_rail'];
 _w = _w + ['rhs_weap_savz58p_rail'];
 _w = _w + ['rhs_weap_aks74u'];
 _w = _w + ['rhs_weap_ak74mr_gp25'];
 _w = _w + ['rhs_weap_svdp_pso1'];
 _w = _w + ['rhs_weap_45th_asval'];
 _w = _w + ['rhs_weap_45th_vss'];
 _w = _w + ['rhs_weap_45th_ak74m_pkas'];
 _w = _w + ['rhs_weap_45th_ak74m_gp25'];
 _w = _w + ['rhs_weap_45th_ak74_ekp1'];
 _w = _w + ['rhs_weap_45th_ak74m_sup'];
 _w = _w + ['KA_VC1_Flamethrower'];
// k hovnu ///////////////////////////////////////////////////////
//_w = _w + ['rhs_weap_ak74m_dtk'];
//_w = _w + ['rhs_weap_ak74m_gp25_dtk'];
//_w = _w + ['rhs_weap_ak74m_plummag_dtk'];
// _w = _w + ['rhs_weap_akm_zenitco01_b33'];
// _w = _w + ['rhs_weap_akmn'];
// _w = _w + ['rhs_weap_akmn_gp25'];
// _w = _w + ['rhs_weap_akmn_gp25_npz'];
// _w = _w + ['rhs_weap_akmn_npz'];
// _w = ['rhs_weap_g36c'];
// _w = _w + ['rhs_weap_g36kv'];
// _w = _w + ['rhs_weap_g36kv_ag36'];
// _w = _w + ['rhs_weap_kar98k'];
// _w = _w + ['rhs_weap_m21a_pbg40'];
// _w = _w + ['rhs_weap_m21a_pr'];
// _w = _w + ['rhs_weap_m21a_pr_pbg40'];
// _w = _w + ['rhs_weap_m21s'];
// _w = _w + ['rhs_weap_m21s_pr'];
// _w = _w + ['rhs_weap_m38_rail'];
// _w = _w + ['rhs_weap_m70ab2'];
// _w = _w + ['rhs_weap_m70b1'];
// _w = _w + ['rhs_weap_m70b1n'];
// _w = _w + ['rhs_weap_m70b3n'];
// _w = _w + ['rhs_weap_m70b3n_pbg40'];
// _w = _w + ['rhs_weap_m82a1'];
// _w = _w + ['rhs_weap_m92'];
// _w = _w + ['rhs_weap_minimi_para_railed'];
// _w = _w + ['rhs_weap_mosin_sbr'];
// _w = _w + ['rhs_weap_ak103_1'];
// _w = _w + ['rhs_weap_ak103_1_npz'];
// _w = _w + ['rhs_weap_ak103_2'];
// _w = _w + ['rhs_weap_ak103_2_npz'];
// _w = _w + ['rhs_weap_ak103_gp25_npz'];
// _w = _w + ['rhs_weap_ak103_npz'];
// _w = _w + ['rhs_weap_ak103_zenitco01'];
// _w = _w + ['rhs_weap_ak103_zenitco01_b33'];
// _w = _w + ['rhs_weap_savz58p_black'];
// _w = _w + ['rhs_weap_savz58p_rail_black'];
// _w = _w + ['rhs_weap_savz58v_black'];
// _w = _w + ['rhs_weap_savz58v_rail_black'];
// _w = _w + ['rhs_weap_ak104'];
// _w = _w + ['rhs_weap_ak104_npz'];
// _w = _w + ['rhs_weap_ak104_zenitco01'];
// _w = _w + ['rhs_weap_ak104_zenitco01_b33'];
// _w = _w + ['rhs_weap_ak74_2'];
// _w = _w + ['rhs_weap_ak74_3'];
// _w = _w + ['rhs_weap_ak74m'];
// _w = _w + ['rhs_weap_pkm'];
// _w = _w + ['rhs_weap_ak74m_2mag'];
// _w = _w + ['rhs_weap_ak74m_2mag_camo'];
// _w = _w + ['rhs_weap_ak74m_2mag_npz'];
// _w = _w + ['rhs_weap_ak74m_camo'];
// _w = _w + ['rhs_weap_ak74m_desert'];
// _w = _w + ['rhs_weap_ak74m_desert_npz'];
// _w = _w + ['rhs_weap_ak74m_fullplum'];
// _w = _w + ['rhs_weap_ak74m_fullplum_gp25'];
// _w = _w + ['rhs_weap_ak74m_fullplum_gp25_npz'];
// _w = _w + ['rhs_weap_ak74m_fullplum_npz'];
// _w = _w + ['rhs_weap_ak74m_gp25_folded'];
// _w = _w + ['rhs_weap_ak74m_gp25_npz'];
// _w = _w + ['rhs_weap_ak74m_npz'];
// _w = _w + ['rhs_weap_ak74m_plummag'];
// _w = _w + ['rhs_weap_ak74m_plummag_npz'];
// _w = _w + ['rhs_weap_ak74m_zenitco01'];
// _w = _w + ['rhs_weap_ak74m_zenitco01_b33'];
// _w = _w + ['rhs_weap_ak74mr'];
// _w = _w + ['rhs_weap_ak74n'];
// _w = _w + ['rhs_weap_ak74n_2'];
// _w = _w + ['rhs_weap_ak74n_2_npz'];
// _w = _w + ['rhs_weap_ak74n_gp25'];
// _w = _w + ['rhs_weap_ak74n_gp25_npz'];
// _w = _w + ['rhs_weap_ak74n_npz'];
// _w = _w + ['rhs_weap_aks74_2'];
// _w = _w + ['rhs_weap_aks74n'];
// _w = _w + ['rhs_weap_aks74n_2'];
// _w = _w + ['rhs_weap_aks74n_2_npz'];
// _w = _w + ['rhs_weap_aks74n_gp25'];
// _w = _w + ['rhs_weap_aks74n_gp25_npz'];
// _w = _w + ['rhs_weap_aks74n_npz'];
// _w = _w + ['rhs_weap_aks74un'];
// _w = _w + ['rhs_weap_asval_grip_npz'];
// _w = _w + ['rhs_weap_asval_npz'];
// _w = _w + ['rhs_weap_pm63'];
// _w = _w + ['rhs_weap_svdp_npz'];
// _w = _w + ['rhs_weap_svdp_wd_npz'];
// _w = _w + ['rhs_weap_svds'];
// _w = _w + ['rhs_weap_svds_npz'];
// _w = _w + ['rhs_weap_vss_grip_npz'];
// _w = _w + ['rhs_weap_vss_npz'];
//_w = _w + ['rhs_weap_svdp_wd'];
//_w = _w + ['rhs_weap_svdp'];
//if (_tiMode) then {_w = _w + ['AKS_74_GOSHAWK'];};
WF_Logic setVariable ['primaryClasses',_w];

/* Secondary. */
_w = ['rhs_weap_rpg26'];
_w = _w + ['rhs_weap_igla'];
_w = _w + ['rhs_weap_rpg7_pgo'];
_w = _w + ['rhs_weap_rshg2'];
_w = _w + ['launch_O_Vorona_green_F'];
WF_Logic setVariable ['secondaryClasses',_w];

//_w =  ['ACE_KORDProxy'];
//_w = _w + ['ACE_6T7TripodProxy'];
//WF_Logic setVariable ['backcontentClasses',_w]; //delete

/* Sidearms. */
_w = ['rhs_weap_makarov_pm'];
_w = _w + ['rhs_weap_pb_6p9'];
_w = _w + ['rhs_weap_pp2000_folded'];
_w = _w + ['rhs_weap_rsp30_white'];
_w = _w + ['rhs_weap_rsp30_green'];
_w = _w + ['rhs_weap_rsp30_red'];
_w = _w + ['rhs_weap_pya'];
_w = _w + ['rhs_weap_tt33'];
WF_Logic setVariable ['sidearmClasses',_w];

/* Throw. */
_w = ['rhs_mag_rgd5'];
_w = _w + ['SmokeShell'];
_w = _w + ['SmokeShellBlue'];
_w = _w + ['SmokeShellGreen'];
_w = _w + ['SmokeShellOrange'];
_w = _w + ['SmokeShellPurple'];
_w = _w + ['SmokeShellRed'];
_w = _w + ['SmokeShellYellow'];
_w = _w + ['Chemlight_red'];
_w = _w + ['Chemlight_green'];
_w = _w + ['Chemlight_blue'];
_w = _w + ['Chemlight_yellow'];
_w = _w + ['HandGrenade'];
_w = _w + ['MiniGrenade'];
_w = _w + ['HandGrenade_Stone'];
_w = _w + ['O_IR_Grenade'];
_w = _w + ['rhs_mag_f1'];
_w = _w + ['rhs_mag_fakel'];
_w = _w + ['rhs_mag_fakels'];
_w = _w + ['rhs_mag_plamyam'];
_w = _w + ['rhs_mag_rdg2_black'];
_w = _w + ['rhs_mag_rdg2_white'];
_w = _w + ['rhs_mag_rgn'];
_w = _w + ['rhs_mag_rgo'];
_w = _w + ['rhs_mag_zarya2'];
_w = _w + ['rhs_mine_pmn2_mag'];
_w = _w + ['rhs_mine_tm62m_mag'];
WF_Logic setVariable ['cargo_throwClasses',_w];

/* Put. */
_w = ['DemoCharge_Remote_Mag'];
_w = _w + ['IEDUrbanSmall_Remote_Mag'];
_w = _w + ['IEDLandSmall_Remote_Mag'];
_w = _w + ['SatchelCharge_Remote_Mag'];
_w = _w + ['IEDUrbanBig_Remote_Mag'];
_w = _w + ['IEDLandBig_Remote_Mag'];
_w = _w + ['ATMine_Range_Mag'];
_w = _w + ['ClaymoreDirectionalMine_Remote_Mag'];
_w = _w + ['APERSMine_Range_Mag'];
_w = _w + ['APERSBoundingMine_Range_Mag'];
_w = _w + ['SLAMDirectionalMine_Wire_Mag'];
_w = _w + ['APERSTripMine_Wire_Mag'];
_w = _w + ['rhs_mag_mine_pfm1'];
_w = _w + ['rhs_mag_mine_ptm1'];
_w = _w + ['rhssaf_mine_pma3_mag'];
_w = _w + ['rhssaf_mine_tma4_mag'];
WF_Logic setVariable ['cargo_putClasses',_w];

/* Uniform. */
_w = ['rhs_uniform_gorka_r_y'];
_w = _w + ['rhs_uniform_mflora_patchless'];
_w = _w + ['rhs_uniform_emr_des_patchless'];
_w = _w + ['rhs_uniform_flora_patchless'];
_w = _w + ['rhs_uniform_flora'];
_w = _w + ['U_O_Wetsuit'];

WF_Logic setVariable ['uniformClasses',_w];

/* Vest. */
_w = ['rhs_6b13_Flora'];
_w = _w + ['rhs_6b23'];
_w = _w + ['rhs_6b23_ML'];
_w = _w + ['rhs_6b43'];
_w = _w + ['rhs_6sh46'];
_w = _w + ['rhs_6sh92'];
_w = _w + ['rhs_6sh92_vsr'];
_w = _w + ['rhs_vydra_3m'];
_w = _w + ['rhs_vest_pistol_holster'];
_w = _w + ['V_RebreatherIR'];
_w = _w + ['rhs_6b23_6sh116_vog_od'];
_w = _w + ['rhs_6b23_6sh92'];
_w = _w + ['rhs_6b23_6sh92_vog'];
_w = _w + ['rhs_6b23_sniper'];
_w = _w + ['rhs_6b23_rifleman'];
_w = _w + ['rhs_6b23_6sh92_vog_headset'];
_w = _w + ['rhs_6b23_6sh92_radio'];
_w = _w + ['rhs_6b23_medic'];
_w = _w + ['rhs_6b13_Flora_6sh92_radio'];
_w = _w + ['rhs_6b13_Flora_6sh92_vog'];
// _w = _w + ['rhs_6b23_6sh116_od'];
// _w = _w + ['rhs_6b23_6sh92_headset_mapcase'];
// _w = _w + ['rhs_6b23_vydra_3m'];
// _w = _w + ['rhs_6b23_engineer'];
// _w = _w + ['rhs_6b23_crewofficer'];
// _w = _w + ['rhs_6b23_crew'];
// _w = _w + ['rhs_6b23_digi_6sh92_Vog_Radio_Spetsnaz'];
// _w = _w + ['rhs_6b23_digi_6sh92_headset_spetsnaz'];
// _w = _w + ['rhs_6b23_digi_6sh92_Spetsnaz'];
// _w = _w + ['rhs_6sh92_vog'];
// _w = _w + ['rhs_6b23_ML_6sh92'];
// _w = _w + ['rhs_6b23_ML_6sh92_vog'];
// _w = _w + ['rhs_6b23_ML_6sh92_vog_headset'];
// _w = _w + ['rhs_6b23_ML_6sh92_headset'];
// _w = _w + ['rhs_6b23_ML_6sh92_headset_mapcase'];
// _w = _w + ['rhs_6b23_ML_6sh92_radio'];
// _w = _w + ['rhs_6b23_ML_vydra_3m'];
// _w = _w + ['rhs_6b23_ML_engineer'];
// _w = _w + ['rhs_6b23_ML_medic'];
// _w = _w + ['rhs_6b23_ML_crewofficer'];
// _w = _w + ['rhs_6b23_ML_sniper'];
// _w = _w + ['rhs_6b23_ML_rifleman'];
// _w = _w + ['rhs_6b23_ML_crew'];
// _w = _w + ['rhs_6b23_digi'];
// _w = _w + ['rhs_6b23_6sh116'];
// _w = _w + ['rhs_6b23_6sh116_vog'];
// _w = _w + ['rhs_6b23_digi_6sh92'];
// _w = _w + ['rhs_6b23_digi_6sh92_vog'];
// _w = _w + ['rhs_6b23_digi_6sh92_vog_headset'];
// _w = _w + ['rhs_6b23_digi_6sh92_headset'];
// _w = _w + ['rhs_6b23_digi_6sh92_headset_mapcase'];
// _w = _w + ['rhs_6b23_digi_6sh92_radio'];
// _w = _w + ['rhs_6b23_digi_vydra_3m'];
// _w = _w + ['rhs_6b23_digi_engineer'];
// _w = _w + ['rhs_6b23_digi_medic'];
// _w = _w + ['rhs_6b23_digi_crewofficer'];
// _w = _w + ['rhs_6b23_digi_sniper'];
// _w = _w + ['rhs_6b23_digi_rifleman'];
// _w = _w + ['rhs_6b23_digi_crew'];
// _w = _w + ['rhs_6b23_digi_6sh92_spetsnaz2'];
// _w = _w + ['rhs_6b23_digi_6sh92_Vog_Spetsnaz'];
// _w = _w + ['rhs_6b23_6sh116_flora'];
// _w = _w + ['rhs_6b23_6sh116_vog_flora'];
// _w = _w + ['rhs_6sh92_vog_headset'];
// _w = _w + ['rhs_6sh92_headset'];
// _w = _w + ['rhs_6sh92_radio'];
// _w = _w + ['rhs_6sh92_vsr_vog'];
// _w = _w + ['rhs_6sh92_vsr_vog_headset'];
// _w = _w + ['rhs_6sh92_vsr_headset'];
// _w = _w + ['rhs_6sh92_vsr_radio'];
// _w = _w + ['rhs_6sh92_digi'];
// _w = _w + ['rhs_6sh92_digi_vog'];
// _w = _w + ['rhs_6sh92_digi_vog_headset'];
// _w = _w + ['rhs_6sh92_digi_headset'];
// _w = _w + ['rhs_6sh92_digi_radio'];
// _w = _w + ['rhs_vest_commander'];
// _w = _w + ['rhs_6b13_Flora_6sh92'];
// _w = _w + ['rhs_6b13_Flora_6sh92_headset_mapcase'];
// _w = _w + ['rhs_6b13_Flora_crewofficer'];
// _w = _w + ['rhs_6b13'];
// _w = _w + ['rhs_6b13_6sh92'];
// _w = _w + ['rhs_6b13_6sh92_vog'];
// _w = _w + ['rhs_6b13_6sh92_headset_mapcase'];
// _w = _w + ['rhs_6b13_6sh92_radio'];
// _w = _w + ['rhs_6b13_crewofficer'];
// _w = _w + ['rhs_6b13_EMR'];
// _w = _w + ['rhs_6b13_EMR_6sh92'];
// _w = _w + ['rhs_6b13_EMR_6sh92_vog'];
// _w = _w + ['rhs_6b13_EMR_6sh92_headset_mapcase'];
// _w = _w + ['rhs_6b13_EMR_6sh92_radio'];
WF_Logic setVariable ['vestClasses',_w];

/* Backpack. */
_w = ['B_Kitbag_mcamo'];
_w = _w + ['rhs_assault_umbts_engineer'];
_w = _w + ['RHS_Podnos_Bipod_Bag'];
_w = _w + ['RHS_Podnos_Gun_Bag'];
_w = _w + ['RHS_Metis_Gun_Bag'];
_w = _w + ['RHS_Metis_Tripod_Bag'];
_w = _w + ['RHS_Kornet_Gun_Bag'];
_w = _w + ['RHS_Kornet_Tripod_Bag'];
_w = _w + ['RHS_AGS30_Tripod_Bag'];
_w = _w + ['RHS_AGS30_Gun_Bag'];
_w = _w + ['rhs_d6_Parachute_backpack'];
_w = _w + ['rhs_assault_umbts_medic'];
_w = _w + ['RHS_DShkM_Gun_Bag'];
_w = _w + ['RHS_DShkM_TripodHigh_Bag'];
_w = _w + ['RHS_DShkM_TripodLow_Bag'];
_w = _w + ['RHS_Kord_Tripod_Bag'];
_w = _w + ['RHS_Kord_Gun_Bag'];
_w = _w + ['RHS_NSV_Tripod_Bag'];
_w = _w + ['RHS_NSV_Gun_Bag'];
_w = _w + ['RHS_SPG9_Gun_Bag'];
_w = _w + ['RHS_SPG9_Tripod_Bag'];
_w = _w + ['rhs_sidor'];
_w = _w + ['rhs_sidorMG'];
_w = _w + ['rhs_rpg'];
_w = _w + ['B_Bergen_mcamo_F'];
_w = _w + ['B_AssaultPack_rgr'];
_w = _w + ['B_FieldPack_oli'];
_w = _w + ['B_Carryall_oli'];
_w = _w + ['B_TacticalPack_oli'];
_w = _w + ['O_UAV_01_backpack_F'];

WF_Logic setVariable ['backpackClasses',_w];

/* Headgear. */
_w = ['rhs_6b26_green'];
_w = _w + ['rhs_6b26_bala_green'];
_w = _w + ['rhs_6b26_ess_green'];
_w = _w + ['rhs_6b26_ess_bala_green'];
_w = _w + ['rhs_6b26'];
_w = _w + ['rhs_6b26_bala'];
_w = _w + ['rhs_6b26_ess'];
_w = _w + ['rhs_6b26_ess_bala'];
_w = _w + ['rhs_6b27m_green'];
_w = _w + ['rhs_6b27m_green_bala'];
_w = _w + ['rhs_6b27m_green_ess'];
_w = _w + ['rhs_6b27m_green_ess_bala'];
_w = _w + ['rhs_6b27m_ml'];
_w = _w + ['rhs_6b27m_ml_bala'];
_w = _w + ['rhs_6b27m_ml_ess'];
_w = _w + ['rhs_6b27m_ML_ess_bala'];
_w = _w + ['rhs_6b27m_digi'];
_w = _w + ['rhs_6b27m_digi_bala'];
_w = _w + ['rhs_6b27m_digi_ess'];
_w = _w + ['rhs_6b27m_digi_ess_bala'];
_w = _w + ['rhs_6b27m'];
_w = _w + ['rhs_6b27m_bala'];
_w = _w + ['rhs_6b27m_ess'];
_w = _w + ['rhs_6b27m_ess_bala'];
_w = _w + ['rhs_6b28_green'];
_w = _w + ['rhs_6b28_green_bala'];
_w = _w + ['rhs_6b28_green_ess'];
_w = _w + ['rhs_6b28_green_ess_bala'];
_w = _w + ['rhs_6b28'];
_w = _w + ['rhs_6b28_bala'];
_w = _w + ['rhs_6b28_ess'];
_w = _w + ['rhs_6b28_ess_bala'];
_w = _w + ['rhs_6b28_flora'];
_w = _w + ['rhs_6b28_flora_bala'];
_w = _w + ['rhs_6b28_flora_ess'];
_w = _w + ['rhs_6b28_flora_ess_bala'];
_w = _w + ['rhs_6b47'];
_w = _w + ['rhs_6b47_bala'];
_w = _w + ['rhs_6b47_ess'];
_w = _w + ['rhs_6b47_ess_bala'];
_w = _w + ['rhs_6b7_1m'];
_w = _w + ['rhs_6b7_1m_emr'];
_w = _w + ['rhs_6b7_1m_bala1_emr'];
_w = _w + ['rhs_6b7_1m_bala2_emr'];
_w = _w + ['rhs_6b7_1m_bala1'];
_w = _w + ['rhs_6b7_1m_olive'];
_w = _w + ['rhs_6b7_1m_bala1_olive'];
_w = _w + ['rhs_6b7_1m_bala2_olive'];
_w = _w + ['rhs_6b7_1m_flora'];
_w = _w + ['rhs_6b7_1m_flora_ns3'];
_w = _w + ['rhs_6b7_1m_bala1_flora'];
_w = _w + ['rhs_6b7_1m_bala2_flora'];
_w = _w + ['rhs_6b7_1m_emr_ess'];
_w = _w + ['rhs_6b7_1m_emr_ess_bala'];
_w = _w + ['rhs_6b7_1m_ess'];
_w = _w + ['rhs_6b7_1m_ess_bala'];
_w = _w + ['rhs_beret_mp1'];
_w = _w + ['rhs_beret_mp2'];
_w = _w + ['rhs_beret_vdv1'];
_w = _w + ['rhs_beret_vdv2'];
_w = _w + ['rhs_beret_vdv3'];
_w = _w + ['rhs_beret_milp'];
_w = _w + ['rhs_altyn_novisor'];
_w = _w + ['rhs_altyn_novisor_bala'];
_w = _w + ['rhs_altyn_novisor_ess'];
_w = _w + ['rhs_altyn_novisor_ess_bala'];
_w = _w + ['rhs_altyn_visordown'];
_w = _w + ['rhs_altyn'];
_w = _w + ['rhs_altyn_bala'];
_w = _w + ['rhs_gssh18'];
_w = _w + ['rhs_zsh7a_mike'];
_w = _w + ['rhs_zsh7a_mike_green'];
_w = _w + ['rhs_zsh7a_mike_green_alt'];
_w = _w + ['rhs_zsh7a_mike_alt'];
_w = _w + ['rhs_zsh7a'];
_w = _w + ['rhs_zsh7a_alt'];
_w = _w + ['rhs_fieldcap'];
_w = _w + ['rhs_fieldcap_helm_ml'];
_w = _w + ['rhs_fieldcap_helm_digi'];
_w = _w + ['rhs_fieldcap_helm'];
_w = _w + ['rhs_fieldcap_vsr'];
_w = _w + ['rhs_fieldcap_ml'];
_w = _w + ['rhs_fieldcap_digi'];
_w = _w + ['rhs_fieldcap_digi2'];
_w = _w + ['rhs_fieldcap_khk'];
_w = _w + ['rhs_Booniehat_digi'];
_w = _w + ['rhs_Booniehat_flora'];
_w = _w + ['rhs_ssh68'];
_w = _w + ['rhs_tsh4'];
_w = _w + ['rhs_tsh4_bala'];
_w = _w + ['rhs_tsh4_ess'];
_w = _w + ['rhs_tsh4_ess_bala'];
_w = _w + ['rhs_beanie_green'];
_w = _w + ['rhs_beanie'];
WF_Logic setVariable ['headgearClasses',_w];

/* Goggle. */
_w = ['G_Aviator'];
_w = _w + ['rhs_balaclava'];
_w = _w + ['rhs_balaclava1_olive'];
_w = _w + ['rhs_scarf'];
WF_Logic setVariable ['goggleClasses',_w];

/* Head-mounted display. */
_w = ['rhs_1PN138'];
WF_Logic setVariable ['hmdClasses',_w];

/* Binocular. */
_w = ['Rangefinder'];
_w = _w + ['rhssaf_zrak_rd7j'];
_w = _w + ['rhs_tr8_periscope'];
_w = _w + ['rhs_pdu4'];
_w = _w + ['Laserdesignator'];
WF_Logic setVariable ['binocularClasses',_w];

/* Accessories. */
_w = ['rhs_acc_1p29'];
_w = _w + ['rhs_acc_1p29_asval'];
_w = _w + ['rhs_acc_1p29_pkp'];
_w = _w + ['rhs_acc_1p63'];
_w = _w + ['rhs_acc_1p78'];
_w = _w + ['rhs_acc_1p78_3d'];
_w = _w + ['rhs_acc_1p87'];
_w = _w + ['rhs_acc_1pn34'];
_w = _w + ['rhs_acc_1pn93_1'];
_w = _w + ['rhs_acc_1pn93_2'];
_w = _w + ['rhs_acc_1pn93_base'];
_w = _w + ['rhs_acc_2dpZenit'];
_w = _w + ['rhs_acc_2dpZenit_ris'];
_w = _w + ['rhs_acc_6p9_suppressor'];
_w = _w + ['rhs_acc_ak5'];
_w = _w + ['rhs_acc_dh520x56'];
_w = _w + ['rhs_acc_dtk'];
_w = _w + ['rhs_acc_dtk1'];
_w = _w + ['rhs_acc_dtk1983'];
_w = _w + ['rhs_acc_dtk1l'];
_w = _w + ['rhs_acc_dtk1p'];
_w = _w + ['rhs_acc_dtk2'];
_w = _w + ['rhs_acc_dtk3'];
_w = _w + ['rhs_acc_dtk4long'];
_w = _w + ['rhs_acc_dtk4screws'];
_w = _w + ['rhs_acc_dtk4short'];
_w = _w + ['rhs_acc_dtkakm'];
_w = _w + ['rhs_acc_ekp1'];
_w = _w + ['rhs_acc_ekp1b'];
_w = _w + ['rhs_acc_ekp1c'];
_w = _w + ['rhs_acc_ekp1d'];
_w = _w + ['rhs_acc_ekp8_02'];
_w = _w + ['rhs_acc_ekp8_02b'];
_w = _w + ['rhs_acc_ekp8_02c'];
_w = _w + ['rhs_acc_ekp8_02d'];
_w = _w + ['rhs_acc_ekp8_18'];
_w = _w + ['rhs_acc_ekp8_18b'];
_w = _w + ['rhs_acc_ekp8_18c'];
_w = _w + ['rhs_acc_ekp8_18d'];
_w = _w + ['rhs_acc_grip_ffg2'];
_w = _w + ['rhs_acc_grip_rk2'];
_w = _w + ['rhs_acc_grip_rk6'];
_w = _w + ['rhs_acc_harris_swivel'];
_w = _w + ['rhs_acc_nita'];
_w = _w + ['rhs_acc_nita_3d'];
_w = _w + ['rhs_acc_pbs1'];
_w = _w + ['rhs_acc_pbs4'];
_w = _w + ['rhs_acc_perst1ik'];
_w = _w + ['rhs_acc_perst1ik_ris'];
_w = _w + ['rhs_acc_perst3'];
_w = _w + ['rhs_acc_perst3_2dp'];
_w = _w + ['rhs_acc_perst3_2dp_h'];
_w = _w + ['rhs_acc_perst3_2dp_light'];
_w = _w + ['rhs_acc_perst3_2dp_light_h'];
_w = _w + ['rhs_acc_perst3_top'];
_w = _w + ['rhs_acc_perst3_top_h'];
_w = _w + ['rhs_acc_pgo7v'];
_w = _w + ['rhs_acc_pgo7v2'];
_w = _w + ['rhs_acc_pgo7v2_ak'];
_w = _w + ['rhs_acc_pgo7v2_asval'];
_w = _w + ['rhs_acc_pgo7v2_pkp'];
_w = _w + ['rhs_acc_pgo7v3'];
_w = _w + ['rhs_acc_pgo7v3_ak'];
_w = _w + ['rhs_acc_pgo7v3_asval'];
_w = _w + ['rhs_acc_pgo7v3_pkp'];
_w = _w + ['rhs_acc_pgo7v_ak'];
_w = _w + ['rhs_acc_pgo7v_asval'];
_w = _w + ['rhs_acc_pgo7v_pkp'];
_w = _w + ['rhs_acc_pgs64'];
_w = _w + ['rhs_acc_pgs64_74u'];
_w = _w + ['rhs_acc_pgs64_74un'];
_w = _w + ['rhs_acc_pkas'];
_w = _w + ['rhs_acc_pkas_asval'];
_w = _w + ['rhs_acc_pkas_pkp'];
_w = _w + ['rhs_acc_pso1m2'];
_w = _w + ['rhs_acc_pso1m21'];
_w = _w + ['rhs_acc_pso1m21_ak'];
_w = _w + ['rhs_acc_pso1m21_pkp'];
_w = _w + ['rhs_acc_pso1m21_svd'];
_w = _w + ['rhs_acc_pso1m2_ak'];
_w = _w + ['rhs_acc_pso1m2_asval'];
_w = _w + ['rhs_acc_pso1m2_pkp'];
_w = _w + ['rhs_acc_rakursPM'];
_w = _w + ['rhs_acc_tgpa'];
_w = _w + ['rhs_acc_tgpv'];
_w = _w + ['rhs_acc_tgpv2'];
_w = _w + ['rhs_acc_uuk'];


_w = _w + ['rhsusf_acc_ACOG'];
_w = _w + ['rhsusf_acc_ACOG2'];
_w = _w + ['rhsusf_acc_ACOG2_3d'];
_w = _w + ['rhsusf_acc_ACOG2_pip'];
_w = _w + ['rhsusf_acc_ACOG2_USMC'];
_w = _w + ['rhsusf_acc_ACOG2_USMC_3d'];
_w = _w + ['rhsusf_acc_ACOG2_USMC_pip'];
_w = _w + ['rhsusf_acc_ACOG3'];
_w = _w + ['rhsusf_acc_ACOG3_3d'];
_w = _w + ['rhsusf_acc_ACOG3_pip'];
_w = _w + ['rhsusf_acc_ACOG3_USMC'];
_w = _w + ['rhsusf_acc_ACOG3_USMC_3d'];
_w = _w + ['rhsusf_acc_ACOG3_USMC_pip'];
_w = _w + ['rhsusf_acc_ACOG_3d'];
_w = _w + ['rhsusf_acc_ACOG_anpvs27'];
_w = _w + ['rhsusf_acc_ACOG_d'];
_w = _w + ['rhsusf_acc_ACOG_d_3d'];
_w = _w + ['rhsusf_acc_ACOG_d_pip'];
_w = _w + ['rhsusf_acc_ACOG_MDO'];
_w = _w + ['rhsusf_acc_ACOG_pip'];
_w = _w + ['rhsusf_acc_ACOG_RMR'];
_w = _w + ['rhsusf_acc_ACOG_RMR_3d'];
_w = _w + ['rhsusf_acc_ACOG_RMR_pip'];
_w = _w + ['rhsusf_acc_ACOG_sa'];
_w = _w + ['rhsusf_acc_ACOG_sa_3d'];
_w = _w + ['rhsusf_acc_ACOG_sa_pip'];
_w = _w + ['rhsusf_acc_ACOG_USMC'];
_w = _w + ['rhsusf_acc_ACOG_USMC_3d'];
_w = _w + ['rhsusf_acc_ACOG_USMC_pip'];
_w = _w + ['rhsusf_acc_ACOG_wd'];
_w = _w + ['rhsusf_acc_ACOG_wd_3d'];
_w = _w + ['rhsusf_acc_ACOG_wd_pip'];
_w = _w + ['rhsusf_acc_anpas13gv1'];
_w = _w + ['rhsusf_acc_anpeq15'];
_w = _w + ['rhsusf_acc_anpeq15_bk'];
_w = _w + ['rhsusf_acc_anpeq15_bk_h'];
_w = _w + ['rhsusf_acc_anpeq15_bk_light'];
_w = _w + ['rhsusf_acc_anpeq15_bk_light_h'];
_w = _w + ['rhsusf_acc_anpeq15_bk_top'];
_w = _w + ['rhsusf_acc_anpeq15_bk_top_h'];
_w = _w + ['rhsusf_acc_anpeq15_h'];
_w = _w + ['rhsusf_acc_anpeq15_light'];
_w = _w + ['rhsusf_acc_anpeq15_light_h'];
_w = _w + ['rhsusf_acc_anpeq15_top'];
_w = _w + ['rhsusf_acc_anpeq15_top_h'];
_w = _w + ['rhsusf_acc_anpeq15_wmx'];
_w = _w + ['rhsusf_acc_anpeq15_wmx_h'];
_w = _w + ['rhsusf_acc_anpeq15_wmx_light'];
_w = _w + ['rhsusf_acc_anpeq15_wmx_light_h'];
_w = _w + ['rhsusf_acc_anpeq15A'];
_w = _w + ['rhsusf_acc_anpeq15side'];
_w = _w + ['rhsusf_acc_anpeq15side_bk'];
_w = _w + ['rhsusf_acc_anpvs27'];
_w = _w + ['rhsusf_acc_ARDEC_M240'];
_w = _w + ['rhsusf_acc_compm4'];
_w = _w + ['rhsusf_acc_ELCAN'];
_w = _w + ['rhsusf_acc_elcan_3d'];
_w = _w + ['rhsusf_acc_ELCAN_ard'];
_w = _w + ['rhsusf_acc_elcan_ard_3d'];
_w = _w + ['rhsusf_acc_ELCAN_ard_pip'];
_w = _w + ['rhsusf_acc_ELCAN_pip'];
_w = _w + ['rhsusf_acc_EOTECH'];
_w = _w + ['rhsusf_acc_eotech_552'];
_w = _w + ['rhsusf_acc_eotech_552_d'];
_w = _w + ['rhsusf_acc_eotech_552_wd'];
_w = _w + ['rhsusf_acc_eotech_xps3'];
_w = _w + ['rhsusf_acc_g33_T1'];
_w = _w + ['rhsusf_acc_g33_T1_flip'];
_w = _w + ['rhsusf_acc_g33_xps3'];
_w = _w + ['rhsusf_acc_g33_xps3_flip'];
_w = _w + ['rhsusf_acc_g33_xps3_tan'];
_w = _w + ['rhsusf_acc_g33_xps3_tan_flip'];
_w = _w + ['rhsusf_acc_grip1'];
_w = _w + ['rhsusf_acc_grip2'];
_w = _w + ['rhsusf_acc_grip2_tan'];
_w = _w + ['rhsusf_acc_grip2_wd'];
_w = _w + ['rhsusf_acc_grip3'];
_w = _w + ['rhsusf_acc_grip3_tan'];
_w = _w + ['rhsusf_acc_grip4'];
_w = _w + ['rhsusf_acc_harris_bipod'];
_w = _w + ['rhsusf_acc_harris_swivel'];
_w = _w + ['rhsusf_acc_LEUPOLDMK4'];
_w = _w + ['rhsusf_acc_LEUPOLDMK4_2'];
_w = _w + ['rhsusf_acc_LEUPOLDMK4_2_d'];
_w = _w + ['rhsusf_acc_M2010S'];
_w = _w + ['rhsusf_acc_M2010S_d'];
_w = _w + ['rhsusf_acc_M2010S_sa'];
_w = _w + ['rhsusf_acc_M2010S_wd'];
_w = _w + ['rhsusf_acc_M2A1'];
_w = _w + ['rhsusf_acc_M8541'];
_w = _w + ['rhsusf_acc_M8541_low'];
_w = _w + ['rhsusf_acc_M8541_low_d'];
_w = _w + ['rhsusf_acc_M8541_low_wd'];
_w = _w + ['rhsusf_acc_M952V'];
_w = _w + ['rhsusf_acc_nt4_black'];
_w = _w + ['rhsusf_acc_nt4_tan'];
_w = _w + ['rhsusf_acc_omega9k'];
_w = _w + ['rhsusf_acc_premier'];
_w = _w + ['rhsusf_acc_premier_anpvs27'];
_w = _w + ['rhsusf_acc_premier_low'];
_w = _w + ['rhsusf_acc_rotex5_grey'];
_w = _w + ['rhsusf_acc_rotex5_tan'];
_w = _w + ['rhsusf_acc_rotex_mp7'];
_w = _w + ['rhsusf_acc_rotex_mp7_aor1'];
_w = _w + ['rhsusf_acc_rotex_mp7_desert'];
_w = _w + ['rhsusf_acc_rotex_mp7_winter'];
_w = _w + ['rhsusf_acc_SF3P556'];
_w = _w + ['rhsusf_acc_SFMB556'];
_w = _w + ['rhsusf_acc_SpecterDR'];
_w = _w + ['rhsusf_acc_SpecterDR_3d'];
_w = _w + ['rhsusf_acc_SpecterDR_A'];
_w = _w + ['rhsusf_acc_SpecterDR_A_3d'];
_w = _w + ['rhsusf_acc_SpecterDR_CX_3D'];
_w = _w + ['rhsusf_acc_SpecterDR_D'];
_w = _w + ['rhsusf_acc_SpecterDR_D_3D'];
_w = _w + ['rhsusf_acc_SpecterDR_OD'];
_w = _w + ['rhsusf_acc_SpecterDR_OD_3D'];
_w = _w + ['rhsusf_acc_SpecterDR_pvs27'];
_w = _w + ['rhsusf_acc_SR25S'];
_w = _w + ['rhsusf_acc_T1_high'];
_w = _w + ['rhsusf_acc_T1_low'];
_w = _w + ['rhsusf_acc_T1_low_fwd'];
_w = _w + ['rhsusf_acc_T1_low_fwd_ak'];
_w = _w + ['rhsusf_acc_wmx'];
_w = _w + ['rhsusf_acc_wmx_bk'];

_w = _w + ['acc_flashlight'];
_w = _w + ['acc_flashlight_pistol'];
_w = _w + ['acc_pointer_IR'];
_w = _w + ['bipod_01_F_blk'];
_w = _w + ['bipod_01_F_mtp'];
_w = _w + ['bipod_01_F_snd'];
_w = _w + ['bipod_02_F_blk'];
_w = _w + ['bipod_02_F_hex'];
_w = _w + ['bipod_02_F_tan'];
_w = _w + ['bipod_03_F_blk'];
_w = _w + ['bipod_03_F_oli'];
_w = _w + ['muzzle_snds_65_TI_blk_F'];
_w = _w + ['muzzle_snds_65_TI_ghex_F'];
_w = _w + ['muzzle_snds_65_TI_hex_F'];
_w = _w + ['muzzle_snds_93mmg'];
_w = _w + ['muzzle_snds_acp'];
_w = _w + ['muzzle_snds_B'];
_w = _w + ['muzzle_snds_H'];
_w = _w + ['muzzle_snds_H_MG'];
_w = _w + ['muzzle_snds_H_SW'];
_w = _w + ['muzzle_snds_L'];
_w = _w + ['muzzle_snds_M'];
_w = _w + ['optic_aco'];
_w = _w + ['optic_ACO_grn'];
_w = _w + ['optic_ACO_grn_smg'];
_w = _w + ['optic_aco_smg'];
_w = _w + ['optic_AMS'];
_w = _w + ['optic_AMS_khk'];
_w = _w + ['optic_AMS_snd'];
_w = _w + ['optic_Arco'];
_w = _w + ['optic_Arco_blk_F'];
_w = _w + ['optic_Arco_ghex_F'];
_w = _w + ['optic_DMS'];
_w = _w + ['optic_DMS_ghex_F'];
_w = _w + ['optic_ERCO_blk_F'];
_w = _w + ['optic_ERCO_khk_F'];
_w = _w + ['optic_ERCO_snd_F'];
_w = _w + ['optic_hamr'];
_w = _w + ['optic_Hamr_khk_F'];
_w = _w + ['optic_Holosight'];
_w = _w + ['optic_Holosight_blk_F'];
_w = _w + ['optic_Holosight_khk_F'];
_w = _w + ['optic_Holosight_smg'];
_w = _w + ['optic_Holosight_smg_blk_F'];
_w = _w + ['optic_Holosight_smg_khk_F'];
_w = _w + ['optic_KHS_blk'];
_w = _w + ['optic_KHS_hex'];
_w = _w + ['optic_KHS_old'];
_w = _w + ['optic_KHS_tan'];
_w = _w + ['optic_LRPS'];
_w = _w + ['optic_LRPS_ghex_F'];
_w = _w + ['optic_LRPS_tna_F'];
_w = _w + ['optic_MRCO'];
_w = _w + ['optic_MRD'];
_w = _w + ['optic_Nightstalker'];
_w = _w + ['optic_NVS'];
_w = _w + ['optic_SOS'];
_w = _w + ['optic_SOS_khk_F'];
_w = _w + ['optic_tws'];
_w = _w + ['optic_tws_mg'];
_w = _w + ['optic_Yorris'];
WF_Logic setVariable ['accessoriesClasses',_w];
		
		//--- Templates.
		_items = ['ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'];

		_d = [getText(configFile >> 'CfgWeapons' >> 'rhs_weap_ak105' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_makarov_pm' >> 'displayName')];
		_p = [getText(configFile >> 'CfgWeapons' >> 'rhs_weap_ak105' >> 'picture')];
		_t = [['rhs_weap_ak105','rhs_weap_makarov_pm']];
		_m = [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_mag_rgd5','rhs_mag_rgd5','SmokeShellRed','SmokeShellRed','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S']];
		_s = [['Rangefinder']];
		_i = [_items];
		_l = [0];
		_b = [true];
/*
		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'AK_107_GL_kobra' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'AK_107_GL_kobra' >> 'picture')];
		_t = _t + [['AK_107_GL_kobra']];
		_m = _m + [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK',
			'rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_mag_rgd5','rhs_mag_rgd5','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25',
			'1Rnd_HE_GP25','1Rnd_HE_GP25']];
		_s = _s + [['Rangefinder']];
		_i = _i + [_items];
		_l = _l + [0];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'AK_107_pso' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'RPG7V' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'AK_107_pso' >> 'picture')];
		_t = _t + [['AK_107_pso','RPG7V']];
		_m = _m + [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','PG7VL','PG7VL','PG7VL']];
		_s = _s + [['Rangefinder','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [1];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'AK_74_GL' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'RPG7V' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'AK_74_GL' >> 'picture')];
		_t = _t + [['AK_74_GL','RPG7V']];
		_m = _m + [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','PG7V',
			'PG7V','PG7V','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25']];
		_s = _s + [['Rangefinder','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [1];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'Sa58V_RCO_EP1' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'RPG7V' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_makarov_pm' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'Sa58V_RCO_EP1' >> 'picture')];
		_t = _t + [['Sa58V_RCO_EP1','RPG7V','rhs_weap_makarov_pm']];
		_m = _m + [['30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','PG7VL','PG7VL','PG7VL',
			'rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S']];
		_s = _s + [['Rangefinder','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [1];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'AKS_74_kobra' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MetisLauncher' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_makarov_pm' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'AKS_74_kobra' >> 'picture')];
		_t = _t + [['AKS_74_kobra','MetisLauncher','rhs_weap_makarov_pm']];
		_m = _m + [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','AT13',
			'rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S']];
		_s = _s + [['Rangefinder','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [3];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'AK_107_kobra' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'Igla' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_makarov_pm' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'AK_107_kobra' >> 'picture')];
		_t = _t + [['AK_107_kobra','Igla','rhs_weap_makarov_pm']];
		_m = _m + [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','Igla',
			'rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S']];
		_s = _s + [['Rangefinder','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'bizon_silenced' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_makarov_pm' >> 'displayName') + '/' + getText(configFile >> 'CfgMagazines' >> 'MineE' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'bizon_silenced' >> 'picture')];
		_t = _t + [['bizon_silenced','rhs_weap_makarov_pm']];
		_m = _m + [['64Rnd_9x19_SD_Bizon','64Rnd_9x19_SD_Bizon','64Rnd_9x19_SD_Bizon','64Rnd_9x19_SD_Bizon','64Rnd_9x19_SD_Bizon','64Rnd_9x19_SD_Bizon','MineE','MineE','MineE',
			'rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S']];
		_s = _s + [['Rangefinder']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [true];

		if (_tiMode) then {
			_d = _d + [getText(configFile >> 'CfgWeapons' >> 'AKS_74_GOSHAWK' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MakarovSD' >> 'displayName') + '/' + getText(configFile >> 'CfgMagazines' >> 'PipeBomb' >> 'displayName')];
			_p = _p + [getText(configFile >> 'CfgWeapons' >> 'AKS_74_GOSHAWK' >> 'picture')];
			_t = _t + [['AKS_74_GOSHAWK','MakarovSD']];
			_m = _m + [['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','PipeBomb','PipeBomb','PipeBomb',
				'8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD']];
			_s = _s + [['Rangefinder','NVGoggles']];
			_i = _i + [_items];
			_l = _l + [2];
			_b = _b + [true];
		};

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'PK' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_makarov_pm' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'PK' >> 'picture')];
		_t = _t + [['PK','rhs_weap_makarov_pm']];
		_m = _m + [['100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','SmokeShellRed','SmokeShellRed','rhs_mag_9x18_8_57N181S',
			'rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S']];
		_s = _s + [['Rangefinder']];
		_i = _i + [_items];
		_l = _l + [0];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'SVD_des_EP1' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MakarovSD' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'SVD_des_EP1' >> 'picture')];
		_t = _t + [['SVD_des_EP1','MakarovSD']];
		_m = _m + [['10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD',
			'10Rnd_762x54_SVD','10Rnd_762x54_SVD','rhs_mag_rgd5','rhs_mag_rgd5','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD',
			'8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD']];
		_s = _s + [['Rangefinder']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'VSS_vintorez' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'Laserdesignator' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MakarovSD' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'VSS_vintorez' >> 'picture')];
		_t = _t + [['VSS_vintorez','Laserdesignator','MakarovSD']];
		_m = _m + [['20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS',
			'20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','rhs_mag_rgd5','Laserbatteries','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD',
			'8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD']];
		_s = _s + [['Binocular_Vector','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'ksvk' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MakarovSD' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'ksvk' >> 'picture')];
		_t = _t + [['ksvk','MakarovSD']];
		_m = _m + [['5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','5Rnd_127x108_KSVK',
			'5Rnd_127x108_KSVK','5Rnd_127x108_KSVK','rhs_mag_rgd5','rhs_mag_rgd5','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD',
			'8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD']];
		_s = _s + [['Binocular_Vector','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [3];
		_b = _b + [false];
*/
		_c = [];
		_totalTemplates = count _d;

		for [{_count = 0},{_count < _totalTemplates},{_count = _count + 1}] do {
			_cost = 0;
			{
				_get = (_x+"_W") Call GetNamespace;
				if (isNil '_get') then {
					_get = _x Call GetNamespace;
				};
				if !(isNil '_get') then {_cost = _cost + (_get select QUERYGEARCOST)};
			} forEach (_t select _count);
			
			{
				_get = _x Call GetNamespace;
				if !(isNil '_get') then {_cost = _cost + (_get select QUERYGEARCOST)};
			} forEach ((_m select _count) + (_s select _count) + (_i select _count));
			
			_c = _c + [_cost];
		};
		WF_Logic setVariable ['templateClasses',_t];
		WF_Logic setVariable ['templateNames',_d];
		WF_Logic setVariable ['templateCosts',_c];
		WF_Logic setVariable ['templatePictures',_p];
		WF_Logic setVariable ['templateMags',_m];
		WF_Logic setVariable ['templateItems',_i];
		WF_Logic setVariable ['templateSpecs',_s];
		WF_Logic setVariable ['templateUpgrades',_l];
		WF_Logic setVariable ['templateAllowed',_b];
	};
};
//снаряжение для красных игроков
['WFBE_EASTDEFAULTWEAPONS',['rhs_weap_akm','rhs_weap_rpg26'],true] Call SetNamespace;
['WFBE_EASTDEFAULTUNIFORM','rhs_uniform_flora_patchless',true] Call SetNamespace;
['WFBE_EASTDEFAULTVEST','rhs_6b23',true] Call SetNamespace;
['WFBE_EASTDEFAULTBACKPACK','rhs_sidor',true] Call SetNamespace;
['WFBE_EASTDEFAULTHEADGEAR','rhs_6b26',true] Call SetNamespace;
['WFBE_EASTDEFAULTGOOGLES','',true] Call SetNamespace;
['WFBE_EASTDEFAULTHMD','',true] Call SetNamespace;
['WFBE_EASTDEFAULTBINOCULAR','rhssaf_zrak_rd7j',true] Call SetNamespace;
['WFBE_EASTDEFAULT_PRIMARYWEAPONITEMS',['',''],true] Call SetNamespace;
['WFBE_EASTDEFAULT_SECONDARYWEAPONITEMS',[],true] Call SetNamespace;
['WFBE_EASTDEFAULT_HANDGUNWEAPONITEMS',[],true] Call SetNamespace;
['WFBE_EASTDEFAULT_PRIMARYWEAPONMAGAZINES',['rhs_30Rnd_762x39mm_tracer'],true] Call SetNamespace;
['WFBE_EASTDEFAULT_SECONDARYWEAPONMAGAZINE','rhs_rpg26_mag',true] Call SetNamespace;
['WFBE_EASTDEFAULT_HANDGUNWEAPONMAGAZINE','',true] Call SetNamespace;
['WFBE_EASTDEFAULT_ITEMSINUNIFORM',['rhs_30Rnd_762x39mm','rhs_30Rnd_762x39mm','rhs_30Rnd_762x39mm','rhs_30Rnd_762x39mm'],true] Call SetNamespace;
['WFBE_EASTDEFAULT_ITEMSINVEST',['rhs_30Rnd_762x39mm','rhs_30Rnd_762x39mm'],true] Call SetNamespace;
['WFBE_EASTDEFAULT_ITEMSINBACKPACK',['FirstAidKit','FirstAidKit','FirstAidKit','rhs_mag_rgd5','rhs_30Rnd_762x39mm','rhs_30Rnd_762x39mm','rhs_mag_rgd5','rhs_mag_rgd5','SmokeShellRed'],true] Call SetNamespace;
['WFBE_EASTDEFAULT_ITEMS',['ItemCompass','ItemMap','ItemGPS','ItemWatch','ItemRadio'],true] Call SetNamespace;
//--- AI Leaders Loadouts.
if (isServer) then {
	//--- No Upgrade.
	['WFBE_EASTLEADERWEAPONS01',['AKS_74','RPG18','rhs_weap_makarov_pm','Rangefinder','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO01',['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','RPG18','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_Backpack01','B_Kitbag_mcamo',true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_ItemToBackpack01',['FirstAidKit','FirstAidKit','FirstAidKit'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_PrimaryWeaponItem01',['rhs_acc_pkas'],true] Call SetNamespace;

	['WFBE_EASTLEADERWEAPONS02',['AK_107_kobra','RPG18','rhs_weap_makarov_pm','Rangefinder','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO02',['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','RPG18','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_Backpack02','B_Kitbag_mcamo',true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_ItemToBackpack02',['FirstAidKit','FirstAidKit','FirstAidKit'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_PrimaryWeaponItem02',['rhs_acc_pkas'],true] Call SetNamespace;

	['WFBE_EASTLEADERWEAPONS03',['PK','rhs_weap_makarov_pm','Rangefinder','ItemRadio','ItemMap'],true] Call SetNamespace;;
	['WFBE_EASTLEADERAMMO03',['100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','rhs_mag_rgd5','rhs_mag_rgd5','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_Backpack03','B_Kitbag_mcamo',true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_ItemToBackpack03',['FirstAidKit','FirstAidKit','FirstAidKit'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS_PrimaryWeaponItem03',['rhs_acc_pkas'],true] Call SetNamespace;
	//--- Upgrade 1.
	['WFBE_EASTLEADERWEAPONS11',['AK_107_kobra','RPG7V','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO11',['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','PG7VL','PG7VL','PG7VL','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS12',['RPK_74','RPG7V','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO12',['75Rnd_545x39_RPK','75Rnd_545x39_RPK','75Rnd_545x39_RPK','75Rnd_545x39_RPK','75Rnd_545x39_RPK','75Rnd_545x39_RPK','PG7VL','PG7VL','PG7VL','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS13',['SVD','MakarovSD','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO13',['10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','rhs_mag_rgd5','rhs_mag_rgd5','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD','8Rnd_9x18_MakarovSD'],true] Call SetNamespace;
	//--- Upgrade 2.
	['WFBE_EASTLEADERWEAPONS21',['AK_107_pso','RPG7V','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO21',['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','PG7VL','PG7VL','PG7VL','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS22',['SVD_des_EP1','RPG7V','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO22',['10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','10Rnd_762x54_SVD','PG7VL','PG7VL','PG7VL','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS23',['Pecheneg','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO23',['100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','100Rnd_762x54_PK','rhs_mag_rgd5','rhs_mag_rgd5','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	//--- Upgrade 3.
	['WFBE_EASTLEADERWEAPONS31',['AK_107_GL_pso','RPG7V','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO31',['rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','rhs_30Rnd_545x39_AK','PG7VL','PG7VL','PG7VL','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25','1Rnd_HE_GP25'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS32',['Sa58V_RCO_EP1','MetisLauncher','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO32',['30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','30Rnd_762x39_SA58','AT13','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
	['WFBE_EASTLEADERWEAPONS33',['VSS_vintorez','rhs_weap_makarov_pm','Rangefinder','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_EASTLEADERAMMO33',['20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','20Rnd_9x39_SP5_VSS','rhs_mag_rgd5','rhs_mag_rgd5','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S','rhs_mag_9x18_8_57N181S'],true] Call SetNamespace;
};