/* US Loadout */
Private ['_tiMode'];
_tiMode = 'WFBE_THERMALIMAGING' Call GetNamespace;
_tiMode = if (_tiMode == 1 || _tiMode == 3) then {true} else {false};

if (!isServer || local player) then {	
if (side player == WEST) then {
/* Misc. */
_w = ['MediKit'];
_w = _w + ['ToolKit'];
_w = _w + ['ItemCompass'];
_w = _w + ['ItemGPS'];
_w = _w + ['ItemMap'];
_w = _w + ['ItemRadio'];
_w = _w + ['ItemWatch'];
_w = _w + ['MineDetector'];
_w = _w + ['B_UavTerminal'];
_w = _w + ['FirstAidKit'];
WF_Logic setVariable ['miscClasses',_w];
	
/* Magazines. */
_m = ["rhs_200rnd_556x45_B_SAW"];
_m = _m + ['rhs_200rnd_556x45_M_SAW'];
_m = _m + ['rhs_200rnd_556x45_T_SAW'];
_m = _m + ['rhs_30Rnd_762x39mm_Savz58'];
_m = _m + ['rhs_30Rnd_762x39mm_Savz58_tracer'];
_m = _m + ['rhs_dummy_mag'];
_m = _m + ['rhs_fgm172a_magazine_AT'];
_m = _m + ['rhs_fgm172b_magazine_MPV'];
_m = _m + ['rhs_fim92_mag'];
_m = _m + ['rhs_LaserFCSMag'];
_m = _m + ['rhs_LaserMag'];
_m = _m + ['rhs_m136_hedp_mag'];
_m = _m + ['rhs_m136_hp_mag'];
_m = _m + ['rhs_m136_mag'];
_m = _m + ['rhs_m72a7_mag'];
_m = _m + ['rhs_m80_mag'];
_m = _m + ['rhs_mag_30Rnd_556x45_M200_Stanag'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855_Stanag'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Green'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Orange'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Red'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855_Stanag_Tracer_Yellow'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855A1_Stanag'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855A1_Stanag_No_Tracer'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Green'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Orange'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red'];
_m = _m + ['rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Yellow'];
_m = _m + ['rhs_mag_30Rnd_556x45_Mk262_Stanag'];
_m = _m + ['rhs_mag_30Rnd_556x45_Mk318_Stanag'];
_m = _m + ['rhs_mag_762x25_8'];
_m = _m + ['rhs_mag_M397_HET'];
_m = _m + ['rhs_mag_m4009'];
_m = _m + ['rhs_mag_M433_HEDP'];
_m = _m + ['rhs_mag_M441_HE'];
_m = _m + ['rhs_mag_m576'];
_m = _m + ['rhs_mag_M585_white'];
_m = _m + ['rhs_mag_m661_green'];
_m = _m + ['rhs_mag_m662_red'];
_m = _m + ['rhs_mag_m713_Red'];
_m = _m + ['rhs_mag_m714_White'];
_m = _m + ['rhs_mag_m715_Green'];
_m = _m + ['rhs_mag_m716_yellow'];
_m = _m + ['rhs_mag_M781_Practice'];
_m = _m + ['rhs_mag_maaws_HE'];
_m = _m + ['rhs_mag_maaws_HEAT'];
_m = _m + ['rhs_mag_maaws_HEDP'];
_m = _m + ['rhs_mag_maaws_ILLUM'];
_m = _m + ['rhs_mag_maaws_SMOKE'];
_m = _m + ['rhs_mag_smaw_HEAA'];
_m = _m + ['rhs_mag_smaw_HEDP'];
_m = _m + ['rhs_mag_smaw_SR'];
_m = _m + ['rhsgref_10rnd_765x17_vz61'];
_m = _m + ['rhsgref_10Rnd_792x57_m76'];
_m = _m + ['rhsgref_1Rnd_00Buck'];
_m = _m + ['rhsgref_1Rnd_Slug'];
_m = _m + ['rhsgref_20rnd_765x17_vz61'];
_m = _m + ['rhsgref_30rnd_556x45_m21'];
_m = _m + ['rhsgref_30rnd_556x45_m21_t'];
_m = _m + ['rhsgref_5Rnd_762x54_m38'];
_m = _m + ['rhsgref_5Rnd_792x57_kar98k'];
_m = _m + ['rhssaf_100rnd_556x45_EPR_G36'];
_m = _m + ['rhssaf_10Rnd_792x57_m76_tracer'];
_m = _m + ['rhssaf_250Rnd_762x54R'];
_m = _m + ['rhssaf_30rnd_556x45_EPR_G36'];
_m = _m + ['rhssaf_30rnd_556x45_MDIM_G36'];
_m = _m + ['rhssaf_30rnd_556x45_SOST_G36'];
_m = _m + ['rhssaf_30rnd_556x45_SPR_G36'];
_m = _m + ['rhssaf_30rnd_556x45_TDIM_G36'];
_m = _m + ['rhssaf_30rnd_556x45_Tracers_G36'];
_m = _m + ['rhsusf_100Rnd_556x45_M200_soft_pouch'];
_m = _m + ['rhsusf_100Rnd_556x45_M855_soft_pouch'];
_m = _m + ['rhsusf_100Rnd_556x45_soft_pouch'];
_m = _m + ['rhsusf_100Rnd_762x51'];
_m = _m + ['rhsusf_100Rnd_762x51_m61_ap'];
_m = _m + ['rhsusf_100Rnd_762x51_m62_tracer'];
_m = _m + ['rhsusf_100Rnd_762x51_m80a1epr'];
_m = _m + ['rhsusf_100Rnd_762x51_m82_blank'];
_m = _m + ['rhsusf_100Rnd_762x51_m993'];
_m = _m + ['rhsusf_10Rnd_762x51_m118_special_Mag'];
_m = _m + ['rhsusf_10Rnd_762x51_m62_Mag'];
_m = _m + ['rhsusf_10Rnd_762x51_m993_Mag'];
_m = _m + ['rhsusf_200Rnd_556x45_M855_soft_pouch'];
_m = _m + ['rhsusf_200Rnd_556x45_soft_pouch'];
_m = _m + ['rhsusf_20Rnd_762x51_m118_special_Mag'];
_m = _m + ['rhsusf_20Rnd_762x51_m62_Mag'];
_m = _m + ['rhsusf_20Rnd_762x51_m993_Mag'];
_m = _m + ['rhsusf_50Rnd_762x51'];
_m = _m + ['rhsusf_50Rnd_762x51_m61_ap'];
_m = _m + ['rhsusf_50Rnd_762x51_m62_tracer'];
_m = _m + ['rhsusf_50Rnd_762x51_m80a1epr'];
_m = _m + ['rhsusf_50Rnd_762x51_m82_blank'];
_m = _m + ['rhsusf_50Rnd_762x51_m993'];
_m = _m + ['rhsusf_5Rnd_00Buck'];
_m = _m + ['rhsusf_5Rnd_300winmag_xm2010'];
_m = _m + ['rhsusf_5Rnd_762x51_m118_special_Mag'];
_m = _m + ['rhsusf_5Rnd_762x51_m62_Mag'];
_m = _m + ['rhsusf_5Rnd_762x51_m993_Mag'];
_m = _m + ['rhsusf_5Rnd_doomsday_Buck'];
_m = _m + ['rhsusf_5Rnd_FRAG'];
_m = _m + ['rhsusf_5Rnd_HE'];
_m = _m + ['rhsusf_5Rnd_Slug'];
_m = _m + ['rhsusf_8Rnd_00Buck'];
_m = _m + ['rhsusf_8Rnd_doomsday_Buck'];
_m = _m + ['rhsusf_8Rnd_FRAG'];
_m = _m + ['rhsusf_8Rnd_HE'];
_m = _m + ['rhsusf_8Rnd_Slug'];
_m = _m + ['rhsusf_launcher_dummy_mag'];
_m = _m + ['rhsusf_mag_10Rnd_STD_50BMG_M33'];
_m = _m + ['rhsusf_mag_10Rnd_STD_50BMG_mk211'];
_m = _m + ['rhsusf_mag_15Rnd_9x19_FMJ'];
_m = _m + ['rhsusf_mag_15Rnd_9x19_JHP'];
_m = _m + ['rhsusf_mag_17Rnd_9x19_FMJ'];
_m = _m + ['rhsusf_mag_17Rnd_9x19_JHP'];
_m = _m + ['rhsusf_mag_40Rnd_46x30_AP'];
_m = _m + ['rhsusf_mag_40Rnd_46x30_FMJ'];
_m = _m + ['rhsusf_mag_40Rnd_46x30_JHP'];
_m = _m + ['rhsusf_mag_6Rnd_M397_HET'];
_m = _m + ['rhsusf_mag_6Rnd_m4009'];
_m = _m + ['rhsusf_mag_6Rnd_M433_HEDP'];
_m = _m + ['rhsusf_mag_6Rnd_M441_HE'];
_m = _m + ['rhsusf_mag_6Rnd_M576_Buckshot'];
_m = _m + ['rhsusf_mag_6Rnd_M585_white'];
_m = _m + ['rhsusf_mag_6Rnd_m661_green'];
_m = _m + ['rhsusf_mag_6Rnd_m662_red'];
_m = _m + ['rhsusf_mag_6Rnd_M713_red'];
_m = _m + ['rhsusf_mag_6Rnd_M714_white'];
_m = _m + ['rhsusf_mag_6Rnd_M715_green'];
_m = _m + ['rhsusf_mag_6Rnd_M716_yellow'];
_m = _m + ['rhsusf_mag_6Rnd_M781_Practice'];
_m = _m + ['rhsusf_mag_7x45acp_MHP'];
_m = _m + ['rhs_fgm148_magazine_AT'];
_m = _m + ['KA_VC1_Flamethrower_Mag'];
WF_Logic setVariable ['magazineClasses',_m];

/* Primary. */

//////////////////////////////////////////////////////////////////
/// gear 0 ///////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////

_w =  ['rhs_weap_Izh18'];
_w =  ['rhs_weap_kar98k'];
_w = _w + ['rhsusf_weap_MP7A2'];
_w = _w + ['rhs_weap_m4_carryhandle'];
_w = _w + ['rhs_weap_m4_m203'];
_w = _w + ['rhs_weap_m16a4_carryhandle'];
_w = _w + ['rhs_weap_m16a4_carryhandle_M203'];
_w = _w + ['rhs_weap_M590_8RD'];
_w = _w + ['rhs_weap_M590_5RD'];
_w = _w + ['rhs_weap_sr25'];
_w = _w + ['rhs_weap_hk416d10'];
_w = _w + ['rhs_weap_hk416d10_m320'];
_w = _w + ['rhs_weap_m32'];
_w = _w + ['rhs_weap_m14ebrri'];
_w = _w + ['rhs_weap_m249'];
_w = _w + ['rhs_weap_m240G'];
_w = _w + ['rhs_weap_g36c'];
_w = _w + ['rhs_weap_g36kv'];
_w = _w + ['rhs_weap_g36kv_ag36'];
_w = _w + ['rhs_weap_XM2010'];
_w = _w + ['rhs_weap_m40a5'];
_w = _w + ['rhs_weap_m24sws'];
_w = _w + ['rhs_weap_M107'];
_w = _w + ['rhs_weap_mk18'];
_w = _w + ['rhs_weap_m21a_pr_pbg40'];
_w = _w + ['KA_VC1_Flamethrower'];
// _w = _w + ['rhs_weap_m4a1'];
// _w = _w + ['rhs_weap_m4a1_carryhandle_mstock'];
// _w = _w + ['rhs_weap_m4_carryhandle_mstock'];
// _w = _w + ['rhs_weap_m4'];
// _w = _w + ['rhs_weap_m16a4'];
// _w = _w + ['rhs_weap_m82a1'];
// _w = _w + ['rhs_weap_hk416d10_LMT'];
// _w = _w + ['rhs_weap_hk416d10_LMT_d'];
// _w = _w + ['rhs_weap_hk416d10_LMT_wd'];
// _w = _w + ['rhs_weap_hk416d145'];
// _w = _w + ['rhs_weap_hk416d145_d'];
// _w = _w + ['rhs_weap_hk416d145_d_2'];
// _w = _w + ['rhs_weap_hk416d145_m320'];
// _w = _w + ['rhs_weap_hk416d145_wd'];
// _w = _w + ['rhs_weap_hk416d145_wd_2'];
// _w = _w + ['rhs_weap_M107_d'];
// _w = _w + ['rhs_weap_M107_w'];
// _w = _w + ['rhs_weap_m24sws_blk'];
// _w = _w + ['rhs_weap_m24sws_ghillie'];
// _w = _w + ['rhs_weap_m240B_CAP'];
// _w = _w + ['rhs_weap_m249_pip_L'];
// _w = _w + ['rhs_weap_m249_pip_L_para'];
// _w = _w + ['rhs_weap_m249_pip_L_vfg'];
// _w = _w + ['rhs_weap_m249_pip_S'];
// _w = _w + ['rhs_weap_m249_pip_S_para'];
// _w = _w + ['rhs_weap_m249_pip_S_vfg'];
// _w = _w + ['rhs_weap_m249_pip'];
// _w = _w + ['rhs_weap_m27iar'];
// _w = _w + ['rhs_weap_m27iar_grip'];
// _w = _w + ['rhs_weap_m40a5_d'];
// _w = _w + ['rhs_weap_m40a5_wd'];
// _w = _w + ['rhs_weap_m4a1_blockII'];
// _w = _w + ['rhs_weap_m4a1_blockII_bk'];
// _w = _w + ['rhs_weap_m4a1_blockII_M203_bk'];
// _w = _w + ['rhs_weap_m4a1_blockII_KAC_bk'];
// _w = _w + ['rhs_weap_m4a1_blockII_d'];
// _w = _w + ['rhs_weap_m4a1_blockII_M203_d'];
// _w = _w + ['rhs_weap_m4a1_blockII_KAC_d'];
// _w = _w + ['rhs_weap_m4a1_blockII_KAC'];
// _w = _w + ['rhs_weap_m4a1_blockII_wd'];
// _w = _w + ['rhs_weap_m4a1_blockII_M203_wd'];
// _w = _w + ['rhs_weap_m4a1_blockII_KAC_wd'];
// _w = _w + ['rhs_weap_m4a1_blockII_M203'];
// _w = _w + ['rhs_weap_m4a1_d'];
// _w = _w + ['rhs_weap_m4a1_d_mstock'];
// _w = _w + ['rhs_weap_m4a1_pmag'];
// _w = _w + ['rhs_weap_m4a1_mstock'];
// _w = _w + ['rhs_weap_m4a1_wd'];
// _w = _w + ['rhs_weap_m4a1_wd_mstock'];
// _w = _w + ['rhs_weap_sr25_d'];
// _w = _w + ['rhs_weap_sr25_ec'];
// _w = _w + ['rhs_weap_sr25_ec_d'];
// _w = _w + ['rhs_weap_sr25_ec_wd'];
// _w = _w + ['rhs_weap_sr25_wd'];
// _w = _w + ['rhs_weap_mk18_bk'];
// _w = _w + ['rhs_weap_mk18_KAC_bk'];
// _w = _w + ['rhs_weap_mk18_d'];
// _w = _w + ['rhs_weap_mk18_KAC_d'];
// _w = _w + ['rhs_weap_mk18_m320'];
// _w = _w + ['rhs_weap_mk18_KAC'];
// _w = _w + ['rhs_weap_mk18_wd'];
// _w = _w + ['rhs_weap_mk18_KAC_wd']; 
// _w = _w + ['rhsusf_weap_MP7A2_aor1'];
// _w = _w + ['rhsusf_weap_MP7A2_desert'];
// _w = _w + ['rhsusf_weap_MP7A2_winter'];
// _w = _w + ['rhs_weap_m16a4_pmag'];
// _w = _w + ['rhs_weap_m16a4_carryhandle_pmag'];
// _w = _w + ['rhs_weap_XM2010_wd'];
// _w = _w + ['rhs_weap_XM2010_sa'];
// _w = _w + ['rhs_weap_XM2010_d'];
// _w = _w + ['rhs_weap_m4_m203S'];
// _w = _w + ['rhs_weap_m4_pmag'];
// _w = _w + ['rhs_weap_m4_mstock'];
// _w = _w + ['rhs_weap_m4_m320'];
// _w = _w + ['rhs_weap_m4_carryhandle_pmag'];
// _w = _w + ['rhs_weap_m4a1_carryhandle'];
// _w = _w + ['rhs_weap_m4a1_carryhandle_m203S'];
// _w = _w + ['rhs_weap_m4a1_carryhandle_pmag'];
// _w = _w + ['rhs_weap_m4a1_carryhandle_m203'];
// _w = _w + ['rhs_weap_m4a1_m203s_d'];
// _w = _w + ['rhs_weap_m4a1_m203s'];
// _w = _w + ['rhs_weap_m4a1_m203s_wd'];
// _w = _w + ['rhs_weap_m4a1_m203'];
// _w = _w + ['rhs_weap_m4a1_m320'];
// _w = _w + ['rhs_weap_minimi_para_railed'];
// _w = _w + ['rhs_weap_m84'];
// _w = _w + ['rhs_weap_m21a_pbg40'];
// _w = _w + ['rhs_weap_m21a_pr_pbg40'];
// _w = _w + ['rhs_weap_m70b1n'];
// _w = _w + ['rhs_weap_m70b3n'];
// _w = _w + ['rhs_weap_m70b3n_pbg40'];
// _w = _w + ['rhs_weap_m21a_pr'];
// _w = _w + ['rhs_weap_m21s'];
// _w = _w + ['rhs_weap_m21s_pr'];
// _w = _w + ['rhs_weap_m70ab2'];
// _w = _w + ['rhs_weap_m70b1'];
// _w = _w + ['rhs_weap_m76'];
// _w = _w + ['rhs_weap_m92'];
// _w = _w + ['rhs_weap_mosin_sbr'];
// _w = _w + ['rhs_weap_savz58p'];
// _w = _w + ['rhs_weap_savz58p_black'];
// _w = _w + ['rhs_weap_savz58p_rail'];
// _w = _w + ['rhs_weap_savz58p_rail_black'];
// _w = _w + ['rhs_weap_savz58v'];
// _w = _w + ['rhs_weap_savz58v_black'];
// _w = _w + ['rhs_weap_savz58v_rail'];
// _w = _w + ['rhs_weap_savz58v_rail_black'];
// _w = _w + ['rhs_weap_savz61'];
// _w = _w + ['rhs_weap_m38'];
// _w = _w + ['rhs_weap_m38_rail'];

WF_Logic setVariable ['primaryClasses',_w];

/* Secondary. */
_w = ['rhs_weap_fgm148'];
_w = _w + ['rhs_weap_fim92'];
_w = _w + ['rhs_weap_M136'];
_w = _w + ['rhs_weap_M136_hedp'];
_w = _w + ['rhs_weap_M136_hp'];
_w = _w + ['rhs_weap_maaws'];
_w = _w + ['rhs_weap_m72a7'];
_w = _w + ['rhs_weap_smaw'];
_w = _w + ['rhs_weap_smaw_green'];
WF_Logic setVariable ['secondaryClasses',_w];

/* Sidearms. */
_w = ['rhsusf_weap_glock17g4'];
_w = _w + ['rhsusf_weap_m9'];
_w = _w + ['rhsusf_weap_m1911a1'];
_w = _w + ['rhs_weap_M320'];
WF_Logic setVariable ['sidearmClasses',_w];

/* Throw. */
_w = ['rhs_mag_an_m14_th3'];
_w = _w + ['rhs_mag_an_m8hc'];
_w = _w + ['rhs_mag_m18_green'];
_w = _w + ['rhs_mag_m18_purple'];
_w = _w + ['rhs_mag_m18_red'];
_w = _w + ['rhs_mag_m18_yellow'];
_w = _w + ['rhs_mag_m67'];
_w = _w + ['rhs_mag_m69'];
_w = _w + ['rhs_mag_m7a3_cs'];
_w = _w + ['rhs_mag_mk3a2'];
_w = _w + ['rhs_mag_mk84'];
_w = _w + ['rhs_mag_nspd'];
_w = _w + ['rhs_mag_nspn_green'];
_w = _w + ['rhs_mag_nspn_red'];
_w = _w + ['rhs_mag_nspn_yellow'];
_w = _w + ['rhs_mine_M19_mag'];
_w = _w + ['rhsgref_mag_rkg3em'];
_w = _w + ['rhsusf_m112_mag'];
_w = _w + ['rhsusf_m112x4_mag'];
_w = _w + ['rhsusf_mine_m14_mag'];
WF_Logic setVariable ['cargo_throwClasses',_w];

/* Put. */
_w = ['DemoCharge_Remote_Mag'];
_w = _w + ['IEDUrbanSmall_Remote_Mag'];
_w = _w + ['IEDLandSmall_Remote_Mag'];
_w = _w + ['SatchelCharge_Remote_Mag'];
_w = _w + ['IEDUrbanBig_Remote_Mag'];
_w = _w + ['IEDLandBig_Remote_Mag'];
_w = _w + ['ATMine_Range_Mag'];
_w = _w + ['ClaymoreDirectionalMine_Remote_Mag'];
_w = _w + ['APERSMine_Range_Mag'];
_w = _w + ['APERSBoundingMine_Range_Mag'];
_w = _w + ['SLAMDirectionalMine_Wire_Mag'];
_w = _w + ['APERSTripMine_Wire_Mag'];
WF_Logic setVariable ['cargo_putClasses',_w];

/* Uniform. */
_w = ['rhs_uniform_acu_ucp'];
_w = _w + ['rhs_uniform_cu_ocp'];
_w = _w + ['rhs_uniform_cu_ucp'];
_w = _w + ['rhs_uniform_FROG01_d'];
_w = _w + ['rhs_uniform_FROG01_wd'];
_w = _w + ['rhs_uniform_g3_blk'];
_w = _w + ['rhs_uniform_g3_m81'];
_w = _w + ['rhs_uniform_g3_mc'];
_w = _w + ['rhs_uniform_g3_rgr'];
_w = _w + ['rhs_uniform_g3_tan'];
_w = _w + ['U_B_Wetsuit'];
_w = _w + ['RWM_ACR_U_vz95_D'];
_w = _w + ['RWM_ACR_U_vz95'];
_w = _w + ['RWM_ACR_U_vz95_D_41'];
_w = _w + ['RWM_ACR_U_afgan'];
_w = _w + ['RWM_ACR_CZ_Black_MP'];
_w = _w + ['RWM_uniform_it_des'];
_w = _w + ['RWM_uniform_it_des_med'];
// _w = _w + ['rhs_uniform_cu_ucp_82nd'];
// _w = _w + ['rhs_uniform_cu_ocp_101st'];
// _w = _w + ['rhs_uniform_cu_ocp_10th'];
// _w = _w + ['rhs_uniform_cu_ocp_1stcav'];
// _w = _w + ['rhs_uniform_cu_ocp_82nd'];
WF_Logic setVariable ['uniformClasses',_w];

/* Vest. */
_w = ['rhsusf_iotv_ocp_Grenadier'];
_w = _w + ['rhsusf_iotv_ucp_Teamleader'];
_w = _w + ['rhsusf_mbav'];
_w = _w + ['rhsusf_spc'];
_w = _w + ['rhsusf_iotv_ocp'];
_w = _w + ['rhsusf_iotv_ucp_Repair'];
_w = _w + ['rhsusf_iotv_ucp_Rifleman'];
_w = _w + ['rhsusf_iotv_ucp_SAW'];
_w = _w + ['rhsusf_iotv_ucp_Squadleader'];
_w = _w + ['rhsusf_iotv_ocp_Medic'];
_w = _w + ['V_RebreatherB'];
_w = _w + ['RWM_V_vz95_Wld_MP'];
_w = _w + ['RWM_V_VZ95_MP'];
_w = _w + ['RWM_V_VZ95_WLD'];
_w = _w + ['BTC_EI_carrier_lite_G'];
_w = _w + ['BTC_EI_carrier_GL_G'];
_w = _w + ['BTC_EI_carrier_lite_2_B'];
// _w = _w + ['rhsusf_iotv_ocp_SAW'];
// _w = _w + ['rhsusf_iotv_ocp_Squadleader'];
// _w = _w + ['rhsusf_iotv_ocp_Teamleader'];
// _w = _w + ['rhsusf_mbav_grenadier'];
// _w = _w + ['rhsusf_mbav_light'];
// _w = _w + ['rhsusf_mbav_mg'];
// _w = _w + ['rhsusf_mbav_medic'];
// _w = _w + ['rhsusf_mbav_rifleman'];
// _w = _w + ['rhsusf_spc_corpsman'];
// _w = _w + ['rhsusf_spc_crewman'];
// _w = _w + ['rhsusf_spc_iar'];
// _w = _w + ['rhsusf_spc_light'];
// _w = _w + ['rhsusf_spc_mg'];
// _w = _w + ['rhsusf_spc_marksman'];
// _w = _w + ['rhsusf_spc_patchless'];
// _w = _w + ['rhsusf_spc_patchless_radio'];
// _w = _w + ['rhsusf_spc_rifleman'];
// _w = _w + ['rhsusf_spc_squadleader'];
// _w = _w + ['rhsusf_spc_teamleader'];
// _w = _w + ['rhsusf_spcs_ocp'];
// _w = _w + ['rhsusf_spcs_ocp_rifleman'];
// _w = _w + ['rhsusf_spcs_ucp_rifleman'];
// _w = _w + ['rhsusf_spcs_ucp'];
WF_Logic setVariable ['vestClasses',_w];

/* Backpack. */
_w = ['B_Kitbag_mcamo'];
_w = _w + ['rhsusf_assault_eagleaiii_ocp'];
_w = _w + ['rhsusf_assault_eagleaiii_ucp'];
_w = _w + ['rhs_Tow_Gun_Bag'];
_w = _w + ['rhs_TOW_Tripod_Bag'];
_w = _w + ['rhs_M252_Gun_Bag'];
_w = _w + ['rhs_M252_Bipod_Bag'];
_w = _w + ['RHS_M2_Gun_Bag'];
_w = _w + ['RHS_M2_Tripod_Bag'];
_w = _w + ['RHS_M2_MiniTripod_Bag'];
_w = _w + ['RHS_Mk19_Gun_Bag'];
_w = _w + ['RHS_Mk19_Tripod_Bag'];
_w = _w + ['B_Parachute'];
_w = _w + ['B_TacticalPack_mcamo'];
_w = _w + ['B_TacticalPack_ocamo'];
_w = _w + ['B_TacticalPack_oli'];
_w = _w + ['B_AssaultPack_khk'];
_w = _w + ['B_AssaultPack_mcamo'];
_w = _w + ['B_Carryall_khk'];
_w = _w + ['B_Carryall_mcamo'];
_w = _w + ['B_Carryall_ocamo'];
_w = _w + ['B_Kitbag_cbr'];
_w = _w + ['B_Kitbag_mcamo'];
_w = _w + ['B_Kitbag_rgr'];
_w = _w + ['B_Kitbag_sgg'];
_w = _w + ['B_FieldPack_khk'];
_w = _w + ['B_FieldPack_ocamo'];
_w = _w + ['B_Bergen_mcamo'];
_w = _w + ['B_Bergen_mcamo_F'];
_w = _w + ['B_Bergen_tna_F'];
_w = _w + ['RWM_B_acr_95'];
_w = _w + ['RWM_B_MedicPack_95'];
_w = _w + ['B_UAV_01_backpack_F'];
// _w = _w + ['rhs_assault_umbts_engineer'];
// _w = _w + ['B_rhsusf_B_BACKPACK'];
// _w = _w + ['rhsusf_assault_eagleaiii_coy'];
// _w = _w + ['rhs_assault_umbts'];
// _w = _w + ['rhsusf_falconii_coy'];
// _w = _w + ['rhsusf_falconii_mc'];
// _w = _w + ['rhsusf_falconii'];
// _w = _w + ['B_AssaultPack_blk'];
// _w = _w + ['B_AssaultPack_cbr'];
// _w = _w + ['B_AssaultPack_dgtl'];
// _w = _w + ['B_AssaultPack_Kerry'];
// _w = _w + ['B_AssaultPack_ocamo'];
// _w = _w + ['B_AssaultPack_rgr'];
// _w = _w + ['B_AssaultPack_sgg'];
// _w = _w + ['B_AssaultPack_tna_F'];
// _w = _w + ['B_Bergen_dgtl_F'];
// _w = _w + ['B_Bergen_hex_F'];
// _w = _w + ['B_Carryall_cbr'];
// _w = _w + ['B_Carryall_ghex_F'];
// _w = _w + ['B_Carryall_oli'];
// _w = _w + ['B_Carryall_oucamo'];
// _w = _w + ['B_FieldPack_blk'];
// _w = _w + ['B_FieldPack_cbr'];
// _w = _w + ['B_FieldPack_ghex_F'];
// _w = _w + ['B_FieldPack_oli'];
// _w = _w + ['B_FieldPack_oucamo'];
// _w = _w + ['B_GMG_01_A_weapon_F'];
// _w = _w + ['B_GMG_01_high_weapon_F'];
// _w = _w + ['B_GMG_01_weapon_F'];
// _w = _w + ['B_HMG_01_A_weapon_F'];
// _w = _w + ['B_HMG_01_high_weapon_F'];
// _w = _w + ['B_HMG_01_support_F'];
// _w = _w + ['B_HMG_01_support_high_F'];
// _w = _w + ['B_HMG_01_weapon_F'];
// _w = _w + ['B_Mortar_01_support_F'];
// _w = _w + ['B_Mortar_01_weapon_F'];
// _w = _w + ['B_Static_Designator_01_weapon_F'];
// _w = _w + ['B_TacticalPack_blk'];
// _w = _w + ['B_TacticalPack_rgr'];
WF_Logic setVariable ['backpackClasses',_w];

/* Headgear. */
_w = ['rhsusf_ach_bare'];
_w = _w + ['rhsusf_ach_bare_des'];
_w = _w + ['rhsusf_ach_bare_des_ess'];
_w = _w + ['rhsusf_ach_bare_des_headset'];
_w = _w + ['rhsusf_ach_bare_des_headset_ess'];
_w = _w + ['rhsusf_ach_bare_ess'];
_w = _w + ['rhsusf_ach_bare_headset'];
_w = _w + ['rhsusf_ach_bare_headset_ess'];
_w = _w + ['rhsusf_ach_bare_semi'];
_w = _w + ['rhsusf_ach_bare_semi_ess'];
_w = _w + ['rhsusf_ach_bare_semi_headset'];
_w = _w + ['rhsusf_ach_bare_semi_headset_ess'];
_w = _w + ['rhsusf_ach_bare_tan'];
_w = _w + ['rhsusf_ach_bare_tan_ess'];
_w = _w + ['rhsusf_ach_bare_tan_headset'];
_w = _w + ['rhsusf_ach_bare_tan_headset_ess'];
_w = _w + ['rhsusf_ach_bare_wood'];
_w = _w + ['rhsusf_ach_bare_wood_ess'];
_w = _w + ['rhsusf_ach_bare_wood_headset'];
_w = _w + ['rhsusf_ach_bare_wood_headset_ess'];
_w = _w + ['rhsusf_ach_helmet_M81'];
_w = _w + ['rhsusf_ach_helmet_ocp'];
_w = _w + ['rhsusf_ach_helmet_ESS_ocp'];
_w = _w + ['rhsusf_ach_helmet_headset_ocp'];
_w = _w + ['rhsusf_ach_helmet_headset_ess_ocp'];
_w = _w + ['rhsusf_ach_helmet_camo_ocp'];
_w = _w + ['rhsusf_ach_helmet_ocp_norotos'];
_w = _w + ['rhsusf_ach_helmet_ucp'];
_w = _w + ['rhsusf_ach_helmet_ESS_ucp'];
_w = _w + ['rhsusf_ach_helmet_headset_ucp'];
_w = _w + ['rhsusf_ach_helmet_headset_ess_ucp'];
_w = _w + ['rhsusf_ach_helmet_ucp_norotos'];
_w = _w + ['rhsusf_cvc_green_helmet'];
_w = _w + ['rhsusf_cvc_green_alt_helmet'];
_w = _w + ['rhsusf_cvc_green_ess'];
_w = _w + ['rhsusf_cvc_helmet'];
_w = _w + ['rhsusf_cvc_alt_helmet'];
_w = _w + ['rhsusf_cvc_ess'];
_w = _w + ['rhs_Booniehat_m81'];
_w = _w + ['rhs_booniehat2_marpatd'];
_w = _w + ['rhs_booniehat2_marpatwd'];
_w = _w + ['rhs_Booniehat_ocp'];
_w = _w + ['rhs_Booniehat_ucp'];
_w = _w + ['rhsusf_Bowman'];
_w = _w + ['rhsusf_bowman_cap'];
_w = _w + ['rhsusf_opscore_aor1'];
_w = _w + ['rhsusf_opscore_aor1_pelt'];
_w = _w + ['rhsusf_opscore_aor1_pelt_nsw'];
_w = _w + ['rhsusf_opscore_aor2'];
_w = _w + ['rhsusf_opscore_aor2_pelt'];
_w = _w + ['rhsusf_opscore_aor2_pelt_nsw'];
_w = _w + ['rhsusf_opscore_bk'];
_w = _w + ['rhsusf_opscore_bk_pelt'];
_w = _w + ['rhsusf_opscore_coy_cover'];
_w = _w + ['rhsusf_opscore_coy_cover_pelt'];
_w = _w + ['rhsusf_opscore_fg'];
_w = _w + ['rhsusf_opscore_fg_pelt'];
_w = _w + ['rhsusf_opscore_fg_pelt_cam'];
_w = _w + ['rhsusf_opscore_fg_pelt_nsw'];
_w = _w + ['rhsusf_opscore_mc_cover'];
_w = _w + ['rhsusf_opscore_mc_cover_pelt'];
_w = _w + ['rhsusf_opscore_mc_cover_pelt_nsw'];
_w = _w + ['rhsusf_opscore_mc_cover_pelt_cam'];
_w = _w + ['rhsusf_opscore_mc'];
_w = _w + ['rhsusf_opscore_mc_pelt'];
_w = _w + ['rhsusf_opscore_mc_pelt_nsw'];
_w = _w + ['rhsusf_opscore_paint'];
_w = _w + ['rhsusf_opscore_paint_pelt'];
_w = _w + ['rhsusf_opscore_paint_pelt_nsw'];
_w = _w + ['rhsusf_opscore_paint_pelt_nsw_cam'];
_w = _w + ['rhsusf_opscore_rg_cover'];
_w = _w + ['rhsusf_opscore_rg_cover_pelt'];
_w = _w + ['rhsusf_opscore_ut'];
_w = _w + ['rhsusf_opscore_ut_pelt'];
_w = _w + ['rhsusf_opscore_ut_pelt_cam'];
_w = _w + ['rhsusf_opscore_ut_pelt_nsw'];
_w = _w + ['rhsusf_opscore_ut_pelt_nsw_cam'];
_w = _w + ['rhsusf_opscore_mar_fg'];
_w = _w + ['rhsusf_opscore_mar_fg_pelt'];
_w = _w + ['rhsusf_opscore_mar_ut'];
_w = _w + ['rhsusf_opscore_mar_ut_pelt'];
_w = _w + ['rhsusf_hgu56p_black'];
_w = _w + ['rhsusf_hgu56p_mask_black'];
_w = _w + ['rhsusf_hgu56p_mask_black_skull'];
_w = _w + ['rhsusf_hgu56p_visor_black'];
_w = _w + ['rhsusf_hgu56p_visor_mask_black'];
_w = _w + ['rhsusf_hgu56p_visor_mask_Empire_black'];
_w = _w + ['rhsusf_hgu56p_visor_mask_black_skull'];
_w = _w + ['rhsusf_hgu56p_green'];
_w = _w + ['rhsusf_hgu56p_mask_green'];
_w = _w + ['rhsusf_hgu56p_mask_green_mo'];
_w = _w + ['rhsusf_hgu56p_visor_green'];
_w = _w + ['rhsusf_hgu56p_visor_mask_green'];
_w = _w + ['rhsusf_hgu56p_visor_mask_green_mo'];
_w = _w + ['rhsusf_hgu56p'];
_w = _w + ['rhsusf_hgu56p_mask'];
_w = _w + ['rhsusf_hgu56p_mask_mo'];
_w = _w + ['rhsusf_hgu56p_mask_skull'];
_w = _w + ['rhsusf_hgu56p_visor'];
_w = _w + ['rhsusf_hgu56p_visor_mask'];
_w = _w + ['rhsusf_hgu56p_visor_mask_mo'];
_w = _w + ['rhsusf_hgu56p_visor_mask_skull'];
_w = _w + ['rhsusf_hgu56p_pink'];
_w = _w + ['rhsusf_hgu56p_mask_pink'];
_w = _w + ['rhsusf_hgu56p_visor_pink'];
_w = _w + ['rhsusf_hgu56p_visor_mask_pink'];
_w = _w + ['rhsusf_hgu56p_saf'];
_w = _w + ['rhsusf_hgu56p_mask_saf'];
_w = _w + ['rhsusf_hgu56p_visor_saf'];
_w = _w + ['rhsusf_hgu56p_visor_mask_saf'];
_w = _w + ['rhsusf_hgu56p_mask_smiley'];
_w = _w + ['rhsusf_hgu56p_visor_mask_smiley'];
_w = _w + ['rhsusf_hgu56p_usa'];
_w = _w + ['rhsusf_hgu56p_visor_usa'];
_w = _w + ['RHS_jetpilot_usaf'];
_w = _w + ['rhsusf_ihadss'];
_w = _w + ['rhsusf_lwh_helmet_M1942'];
_w = _w + ['rhsusf_lwh_helmet_marpatd'];
_w = _w + ['rhsusf_lwh_helmet_marpatd_ess'];
_w = _w + ['rhsusf_lwh_helmet_marpatd_headset'];
_w = _w + ['rhsusf_lwh_helmet_marpatwd'];
_w = _w + ['rhsusf_lwh_helmet_marpatwd_blk_ess'];
_w = _w + ['rhsusf_lwh_helmet_marpatwd_headset_blk'];
_w = _w + ['rhsusf_lwh_helmet_marpatwd_headset'];
_w = _w + ['rhsusf_lwh_helmet_marpatwd_ess'];
_w = _w + ['rhsusf_mich_bare'];
_w = _w + ['rhsusf_mich_bare_alt'];
_w = _w + ['rhsusf_mich_bare_headset'];
_w = _w + ['rhsusf_mich_bare_norotos'];
_w = _w + ['rhsusf_mich_bare_norotos_alt'];
_w = _w + ['rhsusf_mich_bare_norotos_alt_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_arc'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_alt'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_alt_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_headset'];
_w = _w + ['rhsusf_mich_bare_semi'];
_w = _w + ['rhsusf_mich_bare_alt_semi'];
_w = _w + ['rhsusf_mich_bare_semi_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_semi'];
_w = _w + ['rhsusf_mich_bare_norotos_alt_semi'];
_w = _w + ['rhsusf_mich_bare_norotos_alt_semi_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_semi'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_alt_semi'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_alt_semi_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_semi_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_semi_headset'];
_w = _w + ['rhsusf_mich_bare_tan'];
_w = _w + ['rhsusf_mich_bare_alt_tan'];
_w = _w + ['rhsusf_mich_bare_tan_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_tan'];
_w = _w + ['rhsusf_mich_bare_norotos_alt_tan'];
_w = _w + ['rhsusf_mich_bare_norotos_alt_tan_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_tan'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_alt_tan'];
_w = _w + ['rhsusf_mich_bare_norotos_arc_alt_tan_headset'];
_w = _w + ['rhsusf_mich_bare_norotos_tan_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatd'];
_w = _w + ['rhsusf_mich_helmet_marpatd_alt'];
_w = _w + ['rhsusf_mich_helmet_marpatd_alt_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatd_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatd_norotos'];
_w = _w + ['rhsusf_mich_helmet_marpatd_norotos_arc'];
_w = _w + ['rhsusf_mich_helmet_marpatd_norotos_arc_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatd_norotos_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatwd'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_alt'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_alt_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_norotos'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_norotos_arc'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_norotos_arc_headset'];
_w = _w + ['rhsusf_mich_helmet_marpatwd_norotos_headset'];
_w = _w + ['rhsusf_patrolcap_ocp'];
_w = _w + ['rhsusf_patrolcap_ucp'];
_w = _w + ['rhsusf_protech_helmet'];
_w = _w + ['rhsusf_protech_helmet_ess'];
_w = _w + ['rhsusf_protech_helmet_rhino'];
_w = _w + ['rhsusf_protech_helmet_rhino_ess'];
_w = _w + ['RWM_it_beret'];
_w = _w + ['RWM_helmet_it_des'];
_w = _w + ['RWM_H_CZ_vz95_des_med'];
_w = _w + ['RWM_H_CZ_vz95_des'];
_w = _w + ['RWM_H_CZ_vz95_Wld'];
_w = _w + ['RWM_H_baseballcaps_mp'];
_w = _w + ['RWM_helmet_it_wld'];
_w = _w + ['RWM_H_baseballcaps_mp'];
WF_Logic setVariable ['headgearClasses',_w];

/* Goggle. */
_w = ['G_Aviator'];
_w = _w + ['rhsusf_shemagh_grn'];
_w = _w + ['rhsusf_shemagh2_grn'];
_w = _w + ['rhsusf_shemagh_od'];
_w = _w + ['rhsusf_shemagh2_od'];
_w = _w + ['rhsusf_shemagh_tan'];
_w = _w + ['rhsusf_shemagh2_tan'];
_w = _w + ['rhsusf_shemagh_white'];
_w = _w + ['rhsusf_shemagh2_white'];
_w = _w + ['rhsusf_shemagh_gogg_grn'];
_w = _w + ['rhsusf_shemagh2_gogg_grn'];
_w = _w + ['rhsusf_shemagh_gogg_od'];
_w = _w + ['rhsusf_shemagh2_gogg_od'];
_w = _w + ['rhsusf_shemagh_gogg_tan'];
_w = _w + ['rhsusf_shemagh2_gogg_tan'];
_w = _w + ['rhsusf_shemagh_gogg_white'];
_w = _w + ['rhsusf_shemagh2_gogg_white'];
_w = _w + ['rhsusf_oakley_goggles_blk'];
_w = _w + ['rhsusf_oakley_goggles_clr'];
_w = _w + ['rhsusf_oakley_goggles_ylw'];
_w = _w + ['rhs_googles_yellow'];
_w = _w + ['rhs_googles_clear'];
_w = _w + ['rhs_googles_orange'];
_w = _w + ['rhs_googles_black'];
_w = _w + ['rhs_ess_black'];
WF_Logic setVariable ['goggleClasses',_w];

/* Head-mounted display. */
_w = ['rhsusf_ANPVS_14'];
_w = _w + ['rhsusf_ANPVS_15'];
WF_Logic setVariable ['hmdClasses',_w];

/* Binocular. */
_w = ['Rangefinder'];
_w = _w + ['rhssaf_zrak_rd7j'];
_w = _w + ['rhsusf_lrf_Vector21'];
_w = _w + ['lerca_1200_black'];
_w = _w + ['lerca_1200_tan'];
_w = _w + ['Leupold_Mk4'];
_w = _w + ['Laserdesignator_01_khk_F'];
WF_Logic setVariable ['binocularClasses',_w];

/* Accessories. */
_w = ['rhsusf_acc_ACOG'];
_w = _w + ['rhsusf_acc_ACOG2'];
_w = _w + ['rhsusf_acc_ACOG2_3d'];
_w = _w + ['rhsusf_acc_ACOG2_pip'];
_w = _w + ['rhsusf_acc_ACOG2_USMC'];
_w = _w + ['rhsusf_acc_ACOG2_USMC_3d'];
_w = _w + ['rhsusf_acc_ACOG2_USMC_pip'];
_w = _w + ['rhsusf_acc_ACOG3'];
_w = _w + ['rhsusf_acc_ACOG3_3d'];
_w = _w + ['rhsusf_acc_ACOG3_pip'];
_w = _w + ['rhsusf_acc_ACOG3_USMC'];
_w = _w + ['rhsusf_acc_ACOG3_USMC_3d'];
_w = _w + ['rhsusf_acc_ACOG3_USMC_pip'];
_w = _w + ['rhsusf_acc_ACOG_3d'];
_w = _w + ['rhsusf_acc_ACOG_anpvs27'];
_w = _w + ['rhsusf_acc_ACOG_d'];
_w = _w + ['rhsusf_acc_ACOG_d_3d'];
_w = _w + ['rhsusf_acc_ACOG_d_pip'];
_w = _w + ['rhsusf_acc_ACOG_MDO'];
_w = _w + ['rhsusf_acc_ACOG_pip'];
_w = _w + ['rhsusf_acc_ACOG_RMR'];
_w = _w + ['rhsusf_acc_ACOG_RMR_3d'];
_w = _w + ['rhsusf_acc_ACOG_RMR_pip'];
_w = _w + ['rhsusf_acc_ACOG_sa'];
_w = _w + ['rhsusf_acc_ACOG_sa_3d'];
_w = _w + ['rhsusf_acc_ACOG_sa_pip'];
_w = _w + ['rhsusf_acc_ACOG_USMC'];
_w = _w + ['rhsusf_acc_ACOG_USMC_3d'];
_w = _w + ['rhsusf_acc_ACOG_USMC_pip'];
_w = _w + ['rhsusf_acc_ACOG_wd'];
_w = _w + ['rhsusf_acc_ACOG_wd_3d'];
_w = _w + ['rhsusf_acc_ACOG_wd_pip'];
_w = _w + ['rhsusf_acc_anpas13gv1'];
_w = _w + ['rhsusf_acc_anpeq15'];
_w = _w + ['rhsusf_acc_anpeq15_bk'];
_w = _w + ['rhsusf_acc_anpeq15_bk_h'];
_w = _w + ['rhsusf_acc_anpeq15_bk_light'];
_w = _w + ['rhsusf_acc_anpeq15_bk_light_h'];
_w = _w + ['rhsusf_acc_anpeq15_bk_top'];
_w = _w + ['rhsusf_acc_anpeq15_bk_top_h'];
_w = _w + ['rhsusf_acc_anpeq15_h'];
_w = _w + ['rhsusf_acc_anpeq15_light'];
_w = _w + ['rhsusf_acc_anpeq15_light_h'];
_w = _w + ['rhsusf_acc_anpeq15_top'];
_w = _w + ['rhsusf_acc_anpeq15_top_h'];
_w = _w + ['rhsusf_acc_anpeq15_wmx'];
_w = _w + ['rhsusf_acc_anpeq15_wmx_h'];
_w = _w + ['rhsusf_acc_anpeq15_wmx_light'];
_w = _w + ['rhsusf_acc_anpeq15_wmx_light_h'];
_w = _w + ['rhsusf_acc_anpeq15A'];
_w = _w + ['rhsusf_acc_anpeq15side'];
_w = _w + ['rhsusf_acc_anpeq15side_bk'];
_w = _w + ['rhsusf_acc_anpvs27'];
_w = _w + ['rhsusf_acc_ARDEC_M240'];
_w = _w + ['rhsusf_acc_compm4'];
_w = _w + ['rhsusf_acc_ELCAN'];
_w = _w + ['rhsusf_acc_elcan_3d'];
_w = _w + ['rhsusf_acc_ELCAN_ard'];
_w = _w + ['rhsusf_acc_elcan_ard_3d'];
_w = _w + ['rhsusf_acc_ELCAN_ard_pip'];
_w = _w + ['rhsusf_acc_ELCAN_pip'];
_w = _w + ['rhsusf_acc_EOTECH'];
_w = _w + ['rhsusf_acc_eotech_552'];
_w = _w + ['rhsusf_acc_eotech_552_d'];
_w = _w + ['rhsusf_acc_eotech_552_wd'];
_w = _w + ['rhsusf_acc_eotech_xps3'];
_w = _w + ['rhsusf_acc_g33_T1'];
_w = _w + ['rhsusf_acc_g33_T1_flip'];
_w = _w + ['rhsusf_acc_g33_xps3'];
_w = _w + ['rhsusf_acc_g33_xps3_flip'];
_w = _w + ['rhsusf_acc_g33_xps3_tan'];
_w = _w + ['rhsusf_acc_g33_xps3_tan_flip'];
_w = _w + ['rhsusf_acc_grip1'];
_w = _w + ['rhsusf_acc_grip2'];
_w = _w + ['rhsusf_acc_grip2_tan'];
_w = _w + ['rhsusf_acc_grip2_wd'];
_w = _w + ['rhsusf_acc_grip3'];
_w = _w + ['rhsusf_acc_grip3_tan'];
_w = _w + ['rhsusf_acc_grip4'];
_w = _w + ['rhsusf_acc_harris_bipod'];
_w = _w + ['rhsusf_acc_harris_swivel'];
_w = _w + ['rhsusf_acc_LEUPOLDMK4'];
_w = _w + ['rhsusf_acc_LEUPOLDMK4_2'];
_w = _w + ['rhsusf_acc_LEUPOLDMK4_2_d'];
_w = _w + ['rhsusf_acc_M2010S'];
_w = _w + ['rhsusf_acc_M2010S_d'];
_w = _w + ['rhsusf_acc_M2010S_sa'];
_w = _w + ['rhsusf_acc_M2010S_wd'];
_w = _w + ['rhsusf_acc_M2A1'];
_w = _w + ['rhsusf_acc_M8541'];
_w = _w + ['rhsusf_acc_M8541_low'];
_w = _w + ['rhsusf_acc_M8541_low_d'];
_w = _w + ['rhsusf_acc_M8541_low_wd'];
_w = _w + ['rhsusf_acc_M952V'];
_w = _w + ['rhsusf_acc_nt4_black'];
_w = _w + ['rhsusf_acc_nt4_tan'];
_w = _w + ['rhsusf_acc_omega9k'];
_w = _w + ['rhsusf_acc_premier'];
_w = _w + ['rhsusf_acc_premier_anpvs27'];
_w = _w + ['rhsusf_acc_premier_low'];
_w = _w + ['rhsusf_acc_rotex5_grey'];
_w = _w + ['rhsusf_acc_rotex5_tan'];
_w = _w + ['rhsusf_acc_rotex_mp7'];
_w = _w + ['rhsusf_acc_rotex_mp7_aor1'];
_w = _w + ['rhsusf_acc_rotex_mp7_desert'];
_w = _w + ['rhsusf_acc_rotex_mp7_winter'];
_w = _w + ['rhsusf_acc_SF3P556'];
_w = _w + ['rhsusf_acc_SFMB556'];
_w = _w + ['rhsusf_acc_SpecterDR'];
_w = _w + ['rhsusf_acc_SpecterDR_3d'];
_w = _w + ['rhsusf_acc_SpecterDR_A'];
_w = _w + ['rhsusf_acc_SpecterDR_A_3d'];
_w = _w + ['rhsusf_acc_SpecterDR_CX_3D'];
_w = _w + ['rhsusf_acc_SpecterDR_D'];
_w = _w + ['rhsusf_acc_SpecterDR_D_3D'];
_w = _w + ['rhsusf_acc_SpecterDR_OD'];
_w = _w + ['rhsusf_acc_SpecterDR_OD_3D'];
_w = _w + ['rhsusf_acc_SpecterDR_pvs27'];
_w = _w + ['rhsusf_acc_SR25S'];
_w = _w + ['rhsusf_acc_T1_high'];
_w = _w + ['rhsusf_acc_T1_low'];
_w = _w + ['rhsusf_acc_T1_low_fwd'];
_w = _w + ['rhsusf_acc_T1_low_fwd_ak'];
_w = _w + ['rhsusf_acc_wmx'];
_w = _w + ['rhsusf_acc_wmx_bk'];
_w = _w + ['rhs_weap_optic_smaw'];

_w = _w + ['rhs_acc_2dpZenit'];
_w = _w + ['rhs_acc_2dpZenit_ris'];
_w = _w + ['rhs_acc_grip_ffg2'];
_w = _w + ['rhs_acc_grip_rk2'];
_w = _w + ['rhs_acc_grip_rk6'];
_w = _w + ['rhs_acc_harris_swivel'];
_w = _w + ['rhs_acc_perst1ik'];
_w = _w + ['rhs_acc_perst1ik_ris'];
_w = _w + ['rhs_acc_perst3'];
_w = _w + ['rhs_acc_perst3_2dp'];
_w = _w + ['rhs_acc_perst3_2dp_h'];
_w = _w + ['rhs_acc_perst3_2dp_light'];
_w = _w + ['rhs_acc_perst3_2dp_light_h'];
_w = _w + ['rhs_acc_perst3_top'];
_w = _w + ['rhs_acc_perst3_top_h'];

_w = _w + ['acc_flashlight'];
_w = _w + ['acc_flashlight_pistol'];
_w = _w + ['acc_pointer_IR'];
_w = _w + ['bipod_01_F_blk'];
_w = _w + ['bipod_01_F_mtp'];
_w = _w + ['bipod_01_F_snd'];
_w = _w + ['bipod_02_F_blk'];
_w = _w + ['bipod_02_F_hex'];
_w = _w + ['bipod_02_F_tan'];
_w = _w + ['bipod_03_F_blk'];
_w = _w + ['bipod_03_F_oli'];
_w = _w + ['muzzle_snds_65_TI_blk_F'];
_w = _w + ['muzzle_snds_65_TI_ghex_F'];
_w = _w + ['muzzle_snds_65_TI_hex_F'];
_w = _w + ['muzzle_snds_93mmg'];
_w = _w + ['muzzle_snds_acp'];
_w = _w + ['muzzle_snds_B'];
_w = _w + ['muzzle_snds_H'];
_w = _w + ['muzzle_snds_H_MG'];
_w = _w + ['muzzle_snds_H_SW'];
_w = _w + ['muzzle_snds_L'];
_w = _w + ['muzzle_snds_M'];
_w = _w + ['optic_aco'];
_w = _w + ['optic_ACO_grn'];
_w = _w + ['optic_ACO_grn_smg'];
_w = _w + ['optic_aco_smg'];
_w = _w + ['optic_AMS'];
_w = _w + ['optic_AMS_khk'];
_w = _w + ['optic_AMS_snd'];
_w = _w + ['optic_Arco'];
_w = _w + ['optic_Arco_blk_F'];
_w = _w + ['optic_Arco_ghex_F'];
_w = _w + ['optic_DMS'];
_w = _w + ['optic_DMS_ghex_F'];
_w = _w + ['optic_ERCO_blk_F'];
_w = _w + ['optic_ERCO_khk_F'];
_w = _w + ['optic_ERCO_snd_F'];
_w = _w + ['optic_hamr'];
_w = _w + ['optic_Hamr_khk_F'];
_w = _w + ['optic_Holosight'];
_w = _w + ['optic_Holosight_blk_F'];
_w = _w + ['optic_Holosight_khk_F'];
_w = _w + ['optic_Holosight_smg'];
_w = _w + ['optic_Holosight_smg_blk_F'];
_w = _w + ['optic_Holosight_smg_khk_F'];
_w = _w + ['optic_KHS_blk'];
_w = _w + ['optic_KHS_hex'];
_w = _w + ['optic_KHS_old'];
_w = _w + ['optic_KHS_tan'];
_w = _w + ['optic_LRPS'];
_w = _w + ['optic_LRPS_ghex_F'];
_w = _w + ['optic_LRPS_tna_F'];
_w = _w + ['optic_MRCO'];
_w = _w + ['optic_MRD'];
// _w = _w + ['optic_Nightstalker'];
_w = _w + ['optic_NVS'];
_w = _w + ['optic_SOS'];
_w = _w + ['optic_SOS_khk_F'];
// _w = _w + ['optic_tws'];
// _w = _w + ['optic_tws_mg'];
_w = _w + ['optic_Yorris'];
WF_Logic setVariable ['accessoriesClasses',_w];

		//--- Templates.
		_items = ['ItemCompass','ItemGPS','ItemMap','ItemRadio','ItemWatch'];

		_d = [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_CQC' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhsusf_weap_m1911a1' >> 'displayName')];
		_p = [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_CQC' >> 'picture')];
		_t = [['SCAR_L_CQC','rhsusf_weap_m1911a1']];
		_m = [['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_m67','rhs_mag_m67','SmokeShellBlue','SmokeShellBlue','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911']];
		_s = [['Binocular','Binocular_Vector','NVGoggles']];
		_i = [_items];
		_l = [0];
		_b = [true];
/*
		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'M16A4_GL' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'M16A4_GL' >> 'picture')];
		_t = _t + [['M16A4_GL']];
		_m = _m + [['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag',
			'rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_m67','rhs_mag_m67','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203',
			'1Rnd_HE_M203','1Rnd_HE_M203']];
		_s = _s + [['Binocular']];
		_i = _i + [_items];
		_l = _l + [0];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'G36C_camo' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhs_weap_m72a7' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'G36C_camo' >> 'picture')];
		_t = _t + [['G36C_camo','rhs_weap_m72a7']];
		_m = _m + [['30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','rhs_weap_m72a7']];
		_s = _s + [['Binocular']];
		_i = _i + [_items];
		_l = _l + [0];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'SCAR_H_STD_EGLM_Spect' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MAAWS' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'SCAR_H_STD_EGLM_Spect' >> 'picture')];
		_t = _t + [['SCAR_H_STD_EGLM_Spect','MAAWS']];
		_m = _m + [['20rnd_762x51_B_SCAR','20rnd_762x51_B_SCAR','20rnd_762x51_B_SCAR','20rnd_762x51_B_SCAR','20rnd_762x51_B_SCAR','20rnd_762x51_B_SCAR','MAAWS_HEAT',
			'MAAWS_HEAT','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203']];
		_s = _s + [['Binocular','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [3];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_STD_HOLO' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'MAAWS' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_STD_HOLO' >> 'picture')];
		_t = _t + [['SCAR_L_STD_HOLO','MAAWS','M9']];
		_m = _m + [['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','MAAWS_HEAT','MAAWS_HEAT',
			'15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9']];
		_s = _s + [['Binocular_Vector','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'M4A3_CCO_EP1' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'Javelin' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhsusf_weap_m1911a1' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'M4A3_CCO_EP1' >> 'picture')];
		_t = _t + [['M4A3_CCO_EP1','Javelin','rhsusf_weap_m1911a1']];
		_m = _m + [['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','Javelin',
			'DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911']];
		_s = _s + [['Binocular','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [3];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_STD_Mk4CQT' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'Stinger' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_STD_Mk4CQT' >> 'picture')];
		_t = _t + [['SCAR_L_STD_Mk4CQT','Stinger','M9']];
		_m = _m + [['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','Stinger',
			'15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9']];
		_s = _s + [['Binocular','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [false];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_CQC' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9' >> 'displayName') + '/' + getText(configFile >> 'CfgMagazines' >> 'Mine' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'SCAR_L_CQC' >> 'picture')];
		_t = _t + [['SCAR_L_CQC','M9']];
		_m = _m + [['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','Mine','Mine','Mine',
			'15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9','15Rnd_9x19_M9']];
		_s = _s + [['Binocular']];
		_i = _i + [_items];
		_l = _l + [0];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'SCAR_H_CQC_CCO_SD' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9SD' >> 'displayName') + '/' + getText(configFile >> 'CfgMagazines' >> 'PipeBomb' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'SCAR_H_CQC_CCO_SD' >> 'picture')];
		_t = _t + [['SCAR_H_CQC_CCO_SD','M9SD']];
		_m = _m + [['20Rnd_762x51_SB_SCAR','20Rnd_762x51_SB_SCAR','20Rnd_762x51_SB_SCAR','20Rnd_762x51_SB_SCAR','20Rnd_762x51_SB_SCAR','20Rnd_762x51_SB_SCAR','PipeBomb','PipeBomb','PipeBomb',
			'15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD']];
		_s = _s + [['Binocular','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [3];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'DELETE_lmg_M240' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhsusf_weap_m1911a1' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'DELETE_lmg_M240' >> 'picture')];
		_t = _t + [['DELETE_lmg_M240','rhsusf_weap_m1911a1']];
		_m = _m + [['DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','SmokeShellRed','SmokeShellRed','DELETE_7Rnd_45ACP_1911',
			'DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911']];
		_s = _s + [['Binocular']];
		_i = _i + [_items];
		_l = _l + [1];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'M249_EP1' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'rhsusf_weap_m1911a1' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'M249_EP1' >> 'picture')];
		_t = _t + [['M249_EP1','rhsusf_weap_m1911a1']];
		_m = _m + [['200Rnd_556x45_M249','200Rnd_556x45_M249','200Rnd_556x45_M249','200Rnd_556x45_M249','200Rnd_556x45_M249','SmokeShellRed','SmokeShellRed','DELETE_7Rnd_45ACP_1911',
			'DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911']];
		_s = _s + [['Binocular','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [true];

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'M14_EP1' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9SD' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'M14_EP1' >> 'picture')];
		_t = _t + [['M14_EP1','M9SD']];
		_m = _m + [['20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR',
			'20Rnd_762x51_DMR','20Rnd_762x51_DMR','rhs_mag_m67','rhs_mag_m67','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD',
			'15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD']];
		_s = _s + [['Binocular_Vector','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [2];
		_b = _b + [false];
		
		if (_tiMode) then {
			_d = _d + [getText(configFile >> 'CfgWeapons' >> 'M110_TWS_EP1' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'Laserdesignator' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9SD' >> 'displayName')];
			_p = _p + [getText(configFile >> 'CfgWeapons' >> 'M110_TWS_EP1' >> 'picture')];
			_t = _t + [['M110_TWS_EP1','Laserdesignator','M9SD']];
			_m = _m + [['20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR',
				'20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','rhs_mag_m67','Laserbatteries','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD',
				'15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD']];
			_s = _s + [['Binocular_Vector','NVGoggles']];
			_i = _i + [_items];
			_l = _l + [3];
			_b = _b + [false];
		};

		_d = _d + [getText(configFile >> 'CfgWeapons' >> 'm107' >> 'displayName') + '/' + getText(configFile >> 'CfgWeapons' >> 'M9SD' >> 'displayName')];
		_p = _p + [getText(configFile >> 'CfgWeapons' >> 'm107' >> 'picture')];
		_t = _t + [['m107','M9SD']];
		_m = _m + [['10Rnd_127x99_m107','10Rnd_127x99_m107','10Rnd_127x99_m107','10Rnd_127x99_m107','10Rnd_127x99_m107','10Rnd_127x99_m107','10Rnd_127x99_m107','10Rnd_127x99_m107',
			'10Rnd_127x99_m107','10Rnd_127x99_m107','rhs_mag_m67','rhs_mag_m67','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD',
			'15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD']];
		_s = _s + [['Binocular_Vector','NVGoggles']];
		_i = _i + [_items];
		_l = _l + [3];
		_b = _b + [false];
*/
		_c = [];
		_totalTemplates = count _d;

		for [{_count = 0},{_count < _totalTemplates},{_count = _count + 1}] do {
			_cost = 0;
			{
				_get = (_x+"_W") Call GetNamespace;
				if (isNil '_get') then {
					_get = _x Call GetNamespace;
				};
				if !(isNil '_get') then {_cost = _cost + (_get select QUERYGEARCOST)};
			} forEach (_t select _count);
			
			{
				_get = _x Call GetNamespace;
				if !(isNil '_get') then {_cost = _cost + (_get select QUERYGEARCOST)};
			} forEach ((_m select _count) + (_s select _count) + (_i select _count));
			
			_c = _c + [_cost];
		};
		WF_Logic setVariable ['templateClasses',_t];
		WF_Logic setVariable ['templateNames',_d];
		WF_Logic setVariable ['templateCosts',_c];
		WF_Logic setVariable ['templatePictures',_p];
		WF_Logic setVariable ['templateMags',_m];
		WF_Logic setVariable ['templateItems',_i];
		WF_Logic setVariable ['templateSpecs',_s];
		WF_Logic setVariable ['templateUpgrades',_l];
		WF_Logic setVariable ['templateAllowed',_b];
	};
};
//снаряжение для синих игроков
['WFBE_WESTDEFAULTWEAPONS',['rhs_weap_m16a4_carryhandle','rhs_weap_m72a7'],true] Call SetNamespace;
['WFBE_WESTDEFAULTUNIFORM','rhs_uniform_cu_ocp',true] Call SetNamespace;
['WFBE_WESTDEFAULTVEST','rhsusf_iotv_ocp',true] Call SetNamespace;
['WFBE_WESTDEFAULTBACKPACK','B_Kitbag_mcamo',true] Call SetNamespace;
['WFBE_WESTDEFAULTHEADGEAR','rhsusf_mich_bare',true] Call SetNamespace;
['WFBE_WESTDEFAULTGOOGLES','',true] Call SetNamespace;
['WFBE_WESTDEFAULTHMD','',true] Call SetNamespace;
['WFBE_WESTDEFAULTBINOCULAR','rhssaf_zrak_rd7j',true] Call SetNamespace;
['WFBE_WESTDEFAULT_PRIMARYWEAPONITEMS',['rhsusf_acc_SF3P556','rhsusf_acc_anpeq15_bk_light'],true] Call SetNamespace;
['WFBE_WESTDEFAULT_SECONDARYWEAPONITEMS',[],true] Call SetNamespace;
['WFBE_WESTDEFAULT_HANDGUNWEAPONITEMS',[],true] Call SetNamespace;
['WFBE_WESTDEFAULT_PRIMARYWEAPONMAGAZINES',['rhs_mag_30Rnd_556x45_Mk318_Stanag'],true] Call SetNamespace;
['WFBE_WESTDEFAULT_SECONDARYWEAPONMAGAZINE','rhs_m72a7_mag',true] Call SetNamespace;
['WFBE_WESTDEFAULT_HANDGUNWEAPONMAGAZINE','',true] Call SetNamespace;
['WFBE_WESTDEFAULT_ITEMSINUNIFORM',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag'],true] Call SetNamespace;
['WFBE_WESTDEFAULT_ITEMSINVEST',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag'],true] Call SetNamespace;
['WFBE_WESTDEFAULT_ITEMSINBACKPACK',['FirstAidKit','FirstAidKit','FirstAidKit','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_m67','rhs_mag_m67','SmokeShellBlue'],true] Call SetNamespace;
['WFBE_WESTDEFAULT_ITEMS',['ItemCompass','ItemMap','ItemGPS','ItemWatch','ItemRadio'],true] Call SetNamespace;

//--- AI Leaders Loadouts.
if (isServer) then {
	//--- No Upgrade.
	['WFBE_WESTLEADERWEAPONS01',['rhs_weap_m4','rhs_weap_m72a7','Binocular','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO01',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_weap_m72a7','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_Backpack01','B_Kitbag_mcamo',true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_ItemToBackpack01',['FirstAidKit','FirstAidKit','FirstAidKit'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_PrimaryWeaponItem01',['rhsusf_acc_eotech_xps3'],true] Call SetNamespace;

	['WFBE_WESTLEADERWEAPONS02',['DELETE_arifle_M4A3_desert','rhs_weap_m72a7','rhsusf_weap_m1911a1','Binocular','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO02',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_weap_m72a7','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_Backpack02','B_Kitbag_mcamo',true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_ItemToBackpack02',['FirstAidKit','FirstAidKit','FirstAidKit'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_PrimaryWeaponItem02',['rhsusf_acc_eotech_xps3'],true] Call SetNamespace;

	['WFBE_WESTLEADERWEAPONS03',['DELETE_lmg_M240','rhsusf_weap_m1911a1','Binocular','ItemRadio','ItemMap'],true] Call SetNamespace;;
	['WFBE_WESTLEADERAMMO03',['DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','rhs_mag_m67','rhs_mag_m67','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_Backpack03','B_Kitbag_mcamo',true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_ItemToBackpack03',['FirstAidKit','FirstAidKit','FirstAidKit'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS_PrimaryWeaponItem03',['rhsusf_acc_eotech_xps3'],true] Call SetNamespace;

	//--- Upgrade 1.
	['WFBE_WESTLEADERWEAPONS11',['M4A3_CCO_EP1','rhs_weap_m72a7','rhsusf_weap_m1911a1','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO11',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_weap_m72a7','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS12',['G36K_camo','rhs_weap_m72a7','rhsusf_weap_m1911a1','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO12',['30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','rhs_weap_m72a7','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS13',['M14_EP1','M9SD','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO13',['20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','20Rnd_762x51_DMR','rhs_mag_m67','rhs_mag_m67','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD','15Rnd_9x19_M9SD'],true] Call SetNamespace;
	//--- Upgrade 2.
	['WFBE_WESTLEADERWEAPONS21',['SCAR_L_STD_HOLO','MAAWS','rhsusf_weap_m1911a1','Binocular_Vector','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO21',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','MAAWS_HEAT','MAAWS_HEAT','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS22',['G36C_camo','MAAWS','rhsusf_weap_m1911a1','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO22',['30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','30Rnd_556x45_G36','MAAWS_HEAT','MAAWS_HEAT','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS23',['MG36','rhsusf_weap_m1911a1','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO23',['100Rnd_556x45_BetaCMag','100Rnd_556x45_BetaCMag','100Rnd_556x45_BetaCMag','100Rnd_556x45_BetaCMag','100Rnd_556x45_BetaCMag','rhs_mag_m67','rhs_mag_m67','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	//--- Upgrade 3.
	['WFBE_WESTLEADERWEAPONS31',['SCAR_L_CQC_EGLM_Holo','MAAWS','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO31',['rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','rhs_mag_30Rnd_556x45_Mk318_Stanag','MAAWS_HEAT','MAAWS_HEAT','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203','1Rnd_HE_M203'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS32',['SCAR_H_STD_EGLM_Spect','Javelin','rhsusf_weap_m1911a1','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO32',['20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','20Rnd_762x51_B_SCAR','Javelin','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
	['WFBE_WESTLEADERWEAPONS33',['Mk_48_DES_EP1','rhsusf_weap_m1911a1','Binocular','NVGoggles','ItemRadio','ItemMap'],true] Call SetNamespace;
	['WFBE_WESTLEADERAMMO33',['DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','DELETE_100Rnd_TE4_LRT4_Red_Tracer_762x51_Belt_M','rhs_mag_m67','rhs_mag_m67','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911','DELETE_7Rnd_45ACP_1911'],true] Call SetNamespace;
};